### ISSUE TITLE
Clarification/Typo on Statement

### ISSUE THREAD

**Issue by kcubey** [nus-cs2113-AY1920S2/forum#1]
Found on page https://nus-cs2113-ay1920s2.github.io/website/admin/ip-w2.html

Potential clarification needed on above mentioned page, under Section 1, Admin - iP Grading > Project Management section:
> Deliver some deliverables in least in 4 out of weeks 2-7)

**Comment by damithc** [comment]
Thanks for the bug report @kcubey 

Will update as follows:
>Submit _some_ deliverables in at least in 4 out of the 6 iP weeks (i.e., week 2- week 7)

**Comment by damithc** [comment]
Fixed.
