### ISSUE TITLE
Project submission

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#100]
Hello,
Should all v2.1 deliverables including the portfolio go into the final submission folder on LumiNUS? 

Also, it says on the website that for the product demo the submission is to a different folder, though I do not see any other folder on LumiNUS. Will this be created later on?

**Comment by damithc** [comment]
> Should all v2.1 deliverables including the portfolio go into the final submission folder on LumiNUS?

Yes.

> Also, it says on the website that for the product demo the submission is to a different folder, though I do not see any other folder on LumiNUS. Will this be created later on?

Created the folder just now.

**Comment by chaosInTheWild** [comment]
Okay thank you prof!
