### ISSUE TITLE
Loading of package suddently becomes unavailable

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#101]
This is my current IntelliJ:
![image](https://user-images.githubusercontent.com/49268567/78962671-695f0f80-7b27-11ea-96cf-e965e533c780.png)

All the loading suddently becomes unavailable. I have shifted to the original status when every code should be correct, but still cannot work.

**Comment by damithc** [comment]
Some things you can try:
* Refresh the gradle project
* Invalidate cache and restart the IDE
* Re-import the project into intellij

**Comment by JTWang2000** [comment]
I re-import and it worked!. Thanks.

**Comment by JTWang2000** [comment]
I have treid to re-import into Intellij. It works! Thanks.
