### ISSUE TITLE
Page limit for PPP

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#102]
I wonder if the heading and the tail count into the page limit? Those really occupy a lot of space
![image](https://user-images.githubusercontent.com/49228945/78968826-1d689680-7b38-11ea-958f-d813b1488edf.png)

![image](https://user-images.githubusercontent.com/49228945/78968848-2b1e1c00-7b38-11ea-80a4-1b30d8deae50.png)

**Comment by damithc** [comment]
Yes. The page limit takes into account that a significant amount of space is wasted by the template. Try to make the PPP concise; peer evaluators are not going to like it if you make them read a lot. Same applies for other 'tricks' such as using small fonts or narrow margins. It's not enough to meet the page limit in theory; you should also meet it in spirit -- i.e., make the content concise. If the content is concise, evaluators are unlikely to fault you for going over the page limit slightly.

**Comment by SibingWu** [comment]
> Yes. The page limit takes into account that a significant amount of space is wasted by the template. Try to make the PPP concise; peer evaluators are not going to like it if you make them read a lot. Same applies for other 'tricks' such as using small fonts or narrow margins. It's not enough to meet the page limit in theory; you should also meet it in spirit -- i.e., make the content concise. If the content is concise, evaluators are unlikely to fault you for going over the page limit slightly.

OK Got it! Thx Prof!
