### ISSUE TITLE
UG submission

### ISSUE THREAD

**Issue by itskesin** [nus-cs2113-AY1920S2/forum#103]
Hi, 
For our team's UG, it is split into 4 markdown documents [UG link](https://ay1920s2-cs2113t-t12-2.github.io/tp/UserGuide.html). May I know whether I can convert each page into pdf and combine them together ? 

For the team files, do everyone in the team have to submit the UG/DG/JAR file respectively?

**Comment by damithc** [comment]
> For our team's UG, it is split into 4 markdown documents [UG link](https://ay1920s2-cs2113t-t12-2.github.io/tp/UserGuide.html). May I know whether I can convert each page into pdf and combine them together ?

Hmm... this is kind of problematic. For example, our scripts will miss out your UG work not in the main UG file. Is it possible to bring everything back to one file?

> For the team files, do everyone in the team have to submit the UG/DG/JAR file respectively?

No. Only one person needs to submit the team files.

**Comment by itskesin** [comment]
Alright thanks for the prompt reply 😄
