### ISSUE TITLE
Formatting problems of DG

### ISSUE THREAD

**Issue by Shannonwje** [nus-cs2113-AY1920S2/forum#108]
Hi sir, my group's DG seems to be having some formatting issues in terms of the spaces for diagrams. We tried to resize our diagrams but the formatting still seems off. 

Will we be penalised for this?

<img width="389" alt="2020-04-11 (3)" src="https://user-images.githubusercontent.com/42537231/79041118-ce962c00-7c1f-11ea-8ce1-0d270fb5f4eb.png">

<img width="439" alt="2020-04-11 (2)" src="https://user-images.githubusercontent.com/42537231/79041116-cd64ff00-7c1f-11ea-9af1-94795bf4f7e4.png">

**Comment by damithc** [comment]
It's fine @Shannonwje. Not your fault. Some wasted space is not a big deal.

**Comment by Shannonwje** [comment]
Ok thank you Sir.
