### ISSUE TITLE
Java CI check keeps getting cancelled

### ISSUE THREAD

**Issue by GanapathySanathBalaji** [nus-cs2113-AY1920S2/forum#109]
Hi Prof,

![image](https://user-images.githubusercontent.com/59698024/79042966-99dda100-7c2e-11ea-8626-aa37009e98da.png)

Our Java CI check keeps getting cancelled. What might the issue be?
Our group retagged v2.1 because we had to make changes after we released.

**Comment by damithc** [comment]
Could be a github problem. Try pushing a dummy commit.

**Comment by GanapathySanathBalaji** [comment]
Thanks Prof, Will try

**Comment by GanapathySanathBalaji** [comment]
When I created a new PR, the CI doesn't run and it's stuck at the starting state.

![image](https://user-images.githubusercontent.com/59698024/79043851-7f0e2b00-7c34-11ea-9a86-65d5c83fcd56.png)

**Comment by GanapathySanathBalaji** [comment]
Hi Prof, It ended up failing again.

![image](https://user-images.githubusercontent.com/59698024/79043916-dca27780-7c34-11ea-9ef7-db132c2b50e2.png)

**Comment by damithc** [comment]
Rather than create a PR, push a dummy commit directly to the master branch.

**Comment by damithc** [comment]
If it is a GitHub problem, more teams will start failing soon. And it could take a while to rectify. Anyway,  your last commit is just a docs update and the commit before that passed. So, not a big issue, unless you plan to push more code before the deadline.

**Comment by GanapathySanathBalaji** [comment]
Pushing a dummy commit didn't resolve the issue. But thanks a lot Prof, we weren't planning to push any more code.

The mysterious thing is that the code seems to still pass CI on the PR created at the nus-cs2113-AY1920S2 branch.

![image](https://user-images.githubusercontent.com/59698024/79044551-538d3f80-7c38-11ea-898d-40cd4a2e828d.png)

**Comment by jinfayap** [comment]
Github status for workflow actions is up now.

**Comment by GanapathySanathBalaji** [comment]
Thanks for the update.  Our code passes Java CI now.
