### ISSUE TITLE
Repl.it W3 Ex2 & Website W3.2b Exercise Typo

### ISSUE THREAD

**Issue by kcubey** [nus-cs2113-AY1920S2/forum#11]
In both the main website and repl Ex2 (use Rectangle objects), the given code states:

> //TODO: add a line here to set the size of r to 8x10 (width x height)
    //Recommended: use the setSize(int height, int width) method of the Rectangle object

However, the method should be setSize(int width, height) instead

**Comment by damithc** [comment]
Thanks for the bug report @kcubey 
Fixed.
