### ISSUE TITLE
Resizing local images in Markdown

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#110]
Hello, how can I resize images in Markdown? Several images are taking a lot of space in my PPP section. I tried the <img src + width> tags but it didn't work.

Any help would be appreciated!

**Comment by A11riseforme** [comment]
`<img src="images/xxx.jpg" style="zoom:50%;" />`

**Comment by damithc** [comment]
`img width` should work too.
```
<img src="https://www.comp.nus.edu.sg/~damithch/pages/images/guide-cover.png" width="200" />
<img src="https://www.comp.nus.edu.sg/~damithch/pages/images/guide-cover.png" width="400" />
```
<img src="https://www.comp.nus.edu.sg/~damithch/pages/images/guide-cover.png" width="200" />
<img src="https://www.comp.nus.edu.sg/~damithch/pages/images/guide-cover.png" width="400" />

**Comment by brandoncjh** [comment]
Noted, thank you for your help!
