### ISSUE TITLE
Luminus change name function not working

### ISSUE THREAD

**Issue by A11riseforme** [nus-cs2113-AY1920S2/forum#112]
We managed to upload the demo video to LumiNUS on time, but with a wrong name, and we are trying to modify the name using the edit function provided by LumiNUS
![image](https://user-images.githubusercontent.com/9150683/79137008-82481900-7de4-11ea-839d-fb2d1c64b0a6.png)
![image](https://user-images.githubusercontent.com/9150683/79137165-cd622c00-7de4-11ea-863f-cf51f69aca65.png)

Althought we can see that LumiNUS prompted and says `file updated`
![image](https://user-images.githubusercontent.com/9150683/79137076-a0ae1480-7de4-11ea-8676-0036e53f7f35.png)

but the name remains the same:
![image](https://user-images.githubusercontent.com/9150683/79137117-b28fb780-7de4-11ea-91de-05f508b39ec9.png)

In this case, will we get penalized?

**Comment by damithc** [comment]
LumiNUS files feature is a bit buggy.
Delete the original file and upload again?

**Comment by A11riseforme** [comment]
> 
> 
> LumiNUS files feature is a bit buggy.
> Delete the original file and upload again?

would that be counted as a late submission?

**Comment by damithc** [comment]
This is what I see by the way.
![image](https://user-images.githubusercontent.com/1673303/79138121-8d9c4400-7de6-11ea-994a-6b1baaf75887.png)

**Comment by A11riseforme** [comment]
> 
> 
> This is what I see by the way.
> ![image](https://user-images.githubusercontent.com/1673303/79138121-8d9c4400-7de6-11ea-994a-6b1baaf75887.png)

yes, we are trying to edit the name of this file,
![image](https://user-images.githubusercontent.com/9150683/79138203-b7556b00-7de6-11ea-81ca-6df35e9e5efe.png)
because the previous one has exceed the time limit by twenty seconds. =(

**Comment by damithc** [comment]
We can take the previous file if you want. Extra 20 seconds can be forgiven.

**Comment by A11riseforme** [comment]
> 
> 
> We can take the previous file if you want. Extra 20 seconds can be forgiven.

Noted with thanks Prof! We will delete the second one.

**Comment by A11riseforme** [comment]
> 
> 
> We can take the previous file if you want. Extra 20 seconds can be forgiven.

Hi Prof, I think the buggy LumiNUS is not allowing us to delete file either. So please use the first one with the correct name instead of the second one. Sorry for the inconvenience caused.

**Comment by damithc** [comment]
Deleted.
