### ISSUE TITLE
Possible typo in PE Phase 3 instructions

### ISSUE THREAD

**Issue by JLoh579** [nus-cs2113-AY1920S2/forum#113]
![image](https://user-images.githubusercontent.com/42561929/79210849-04cde880-7e78-11ea-92d9-ed0f14ca24f6.png)
Hello prof,
It seems the CATcher profile indicated under the 'PE Phase 3: Tester Response' section might be a typo

**Comment by damithc** [comment]
Thanks for the heads up @JLoh579 
Fixed.
