### ISSUE TITLE
Design Problem VS Real Bugs

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#114]
@damithc Professor, in terms of bug response, I have a question:
Some bugs reported are more like design problem(maybe not designed in a considerate way) rather than real bug. The designer allows some cases to happen on purpose(e.g. allow some repetitive inputs/extra parameters),  but such cases were reported as bugs by testers. In such case shall we still consider it as real bugs or shall we reject it?

**Comment by damithc** [comment]
If the behavior is intended, was it documented? If not, is there a good justification for that behavior compared to alternatives? If the answer to is yes to either question, it can be argued as 'not a bug'.

**Comment by SibingWu** [comment]
> If the behavior is intended, was it documented? If not, is there a good justification for that behavior compared to alternatives? If the answer to is yes to either question, it can be argued as 'not a bug'.

Noted with thx!

**Comment by SibingWu** [comment]
@damithc Prof, what if a certain bug exist because we are not skillful enough to implement it now? e.g. check if it is a valid email address

**Comment by damithc** [comment]
> @damithc Prof, what if a certain bug exist because we are not skillful enough to implement it now? e.g. check if it is a valid email address

High development cost (in terms of skill or time) is a valid justification for not implementing a feature.

**Comment by SibingWu** [comment]
> @damithc Prof, what if a certain bug exist because we are not skillful enough to implement it now? e.g. check if it is a valid email address
> 
> High development cost (in terms of skill or time) is a valid justification for not implementing a feature.

Thx prof!
