### ISSUE TITLE
Unable to upload image in Catcher for dev response

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#115]
<img width="721" alt="Screen Shot 2020-04-15 at 20 15 59" src="https://user-images.githubusercontent.com/31772358/79336389-3c12c700-7f56-11ea-9a69-bae26cc4b1ec.png">
I always get Http Error when I try to upload files for our team's dev response in Catcher. Is this an issue with Catcher or is it my problem? This function worked today during the PE.

**Comment by SibingWu** [comment]
I encountered the same error too when I tried to upload screenshot

**Comment by damithc** [comment]
All the time or some of the time? Others have managed to upload screenshots though.

**Comment by SibingWu** [comment]
> All the time or some of the time? Others have managed to upload screenshots though.

I tried to upload again but encounter the error again

**Comment by Zhilin-Huang** [comment]
> All the time or some of the time? Others have managed to upload screenshots though.

For me it's all the time (I tried 5~10 times for one image). It seems that the last time someone uploaded screenshots was 1hr ago?

**Comment by damithc** [comment]
We are able to replicate the problem. CATcher team is looking into it.

**Comment by damithc** [comment]
@Zhilin-Huang @SibingWu Can you try again?

**Comment by Zhilin-Huang** [comment]
> @Zhilin-Huang @SibingWu Can you try again?

I was able to upload an image just now. Thanks Prof!

**Comment by Zhilin-Huang** [comment]
> @Zhilin-Huang @SibingWu Can you try again?

I was able to upload an image just now. Thanks Prof!

**Comment by damithc** [comment]
Great. It turns out to be a permission issue. Thanks to the CATcher dev team for quick troubleshooting.
