### ISSUE TITLE
Self invocation in UML sequence

### ISSUE THREAD

**Issue by MeLoveCarbs** [nus-cs2113-AY1920S2/forum#116]
Is it okay for self-invocation methods to be drawn like this? 
![capture](https://user-images.githubusercontent.com/36870088/79363745-e270c380-7f7a-11ea-932a-b1613b42116f.png)

**Comment by damithc** [comment]
Yes, if it does not lead to any ambiguities. The activation bar (even for self-invocations) is optional.

**Comment by MeLoveCarbs** [comment]
thanks!
