### ISSUE TITLE
Typo in CS2113 website

### ISSUE THREAD

**Issue by rdimaio** [nus-cs2113-AY1920S2/forum#117]
In [PE Phase 3: Tester Response](https://nus-cs2113-ay1920s2.github.io/website/admin/tp-deliverables.html#pe-phase-3-tester-response-2) 

![image](https://user-images.githubusercontent.com/35903974/79681102-a6bf4d80-8249-11ea-9165-2ccbafa6dfc9.png)

`tye.DocumentationBug` should be `type.DocumentationBug`

**Comment by damithc** [comment]
Thanks for the bug report @rdimaio 
Fixed.
