### ISSUE TITLE
Information about final exam

### ISSUE THREAD

**Issue by g-lilian** [nus-cs2113-AY1920S2/forum#119]
If it is not too early to ask, may I know more about the procedures for the final exam? It is mentioned that it will be open-book. Since the exam is now online, can we refer to the online textbook directly? Will the practice paper be released soon?

**Comment by damithc** [comment]
Will settle all that before the end of this week @g-lilian 
Yes, you will be allowed to refer to the soft copy version of the textbook during the exam.

**Comment by g-lilian** [comment]
Noted, thanks!
