### ISSUE TITLE
(A-TextUiTesting) Error: Could not find or load main class Main

### ISSUE THREAD

**Issue by wangqinNick** [nus-cs2113-AY1920S2/forum#12]
I tried to implement the automated text ui texting and followed the Text UI Testing Tutorial in the repo. 
I have trouble in updating the java / javac commands to match my main class. The terminal output is:
      Error: Could not find or load main class Main
      Caused by: java.lang.ClassNotFoundException: Main

My main class's address is 
      /Users/xxx/Documents/cs2113T/ip/src/seedu/duke

How should I edited these two lines:
      if ! javac -cp ../src -Xlint:none -d ../bin ../src/main/java/Duke.java
      java -classpath ../bin Duke < input.txt > ACTUAL.TXT

Thanks very much.

**Comment by damithc** [comment]
@wangqinNick you seem to be using java packages, a topic we have not covered yet. In the meantime, [this article](https://www.webucator.com/how-to/how-compile-packages-java.cfm) might help.

Also, if you followed the given Duke code, you should have a `main` folder in your source path, which don't seem to be in the path you have quoted `/Users/xxx/Documents/cs2113T/ip/src/seedu/duke`
![image](https://user-images.githubusercontent.com/1673303/73077781-d0dbca80-3efb-11ea-87f4-555f3df49ab8.png)

**Comment by wangqinNick** [comment]
> @wangqinNick you seem to be using java packages, a topic we have not covered yet. In the meantime, [this article](https://www.webucator.com/how-to/how-compile-packages-java.cfm) might help.
> 
> Also, if you followed the given Duke code, you should have a `main` folder in your source path, which don't seem to be in the path you have quoted `/Users/xxx/Documents/cs2113T/ip/src/seedu/duke`
> ![image](https://user-images.githubusercontent.com/1673303/73077781-d0dbca80-3efb-11ea-87f4-555f3df49ab8.png)

Thanks, I edited the file structure and runtest.sh can locate my Main.java. 
But it can not compile the package inside the package . 

../src/main/java/Main.java:1: error: package commands does not exist
import commands.Command;
