### ISSUE TITLE
Topics for the final

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#122]
Hello Prof,

I have noticed that in the PDF version of the textbook, it does not include certain sections such as the Intellij section under Tools and also the supplementary topics which include the C++ to Java. Will these excluded sections be examinable in the final?

**Comment by damithc** [comment]
Intellij is not examinable but you should have a general idea about IDEs.
The exam doesn't test your Java knowledge but it assumes you already know Java to the extent it was used in the module activities such as iP and tP. For example, an exam question can give a Java code fragment and ask about coding standard violations in that code.

**Comment by chaosInTheWild** [comment]
Ah okay that makes sense. Thank you prof!
