### ISSUE TITLE
Unable to view extra sample questions in dry-run quiz

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#123]
Hi Prof, may I know where can I find the extra sample questions for the dry run quiz as per the email? Looked in the attempt history but only the original questions were there.

**Comment by damithc** [comment]
@brandoncjh I suspect you have to attempt the quiz again to see the extra questions.

**Comment by brandoncjh** [comment]
Got it, thanks prof!
