### ISSUE TITLE
Coding Standard Violation question in exam dry-run

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#124]
I wonder why the indentation here is not regarded as a violation? The indentation between line 1 and 2 seems to be different from line 2 and 3
![image](https://user-images.githubusercontent.com/49228945/80811141-dda54400-8bf7-11ea-8627-379ec4fc17c7.png)

**Comment by damithc** [comment]
You are right, that's another violation (unintended). I've corrected it.

**Comment by SibingWu** [comment]
> You are right, that's another violation (unintended). I've corrected it.

OK!
