### ISSUE TITLE
Repl.it W3 Ex10

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#13]
Hello, my program for Repl.it W3 Ex10 keeps failing the final test case, even though I am able to get the required output. It passes the other 2 test cases when submitting, may I know is there some sort of time limit for the program or any other issue?

![capture1](https://user-images.githubusercontent.com/54733974/73089390-1787ef80-3f11-11ea-8abf-b18b993aefad.PNG)
![capture2](https://user-images.githubusercontent.com/54733974/73089389-16ef5900-3f11-11ea-8513-1a96d4ed8218.PNG)

**Comment by damithc** [comment]
@brandoncjh there is no time limit. Can you post your code here so that someone else can take a stab at figuring out the problem?

**Comment by brandoncjh** [comment]
```java
import java.util.Scanner;
import java.util.Arrays;

public class Main {

    // You can add more methods here
    public static String[] filterExpenses(String[] words){
        String[] results = new String[words.length];
        int currCount = 0;  //keep track of the index of next free space in validItems
        for (String word : words){
            if (word.substring(0,1).equals("$")){
                results[currCount] = word;
                currCount++;
            }
        }
        //print the 2nd line of output
        System.out.println("Expenses in overseas currency:" + Arrays.toString(Arrays.copyOf(results, currCount)));
        return Arrays.copyOf(results, currCount);
    }

    public static void printTotal(String[] args){
        double total = 0;
        //add floats together
        for (String arg: args){
            //get rid of the preceding $ char and convert value to double
            double currItemValue = Double.parseDouble(arg.substring(1, arg.length()));
            total += 1.7 * currItemValue;   //convert exchange rate
        }
        
        //convert final value to string, print $ + final value
        System.out.println("Total in local currency: $" + String.format("%.2f", total));
    }

    public static void main(String[] args) {
        String line;
        Scanner in = new Scanner(System.in);

        System.out.print("Your expenses while overseas?");
       // TODO: add your code here
       line = in.nextLine();
       String[] separated = line.split(" ");
       printTotal(filterExpenses(separated));
    }
}
```
Apologies for the delay!

**Comment by damithc** [comment]
@brandoncjh for future reference https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Let's wait for a bit to see if anyone in the class can help.

**Comment by brandoncjh** [comment]
Hi Prof, have resolved the issue! I didn't realize the last test case differs from the other two in that it is preceded by a trailing whitespace. This is resolved by adding a `.trim()` before the split function in the 2nd last line of main.

Thank you for your help!
