### ISSUE TITLE
[W3.5] compareTo example missing information

### ISSUE THREAD

**Issue by Bencotti** [nus-cs2113-AY1920S2/forum#14]
This example was quite confusing since there was incomplete information in the example.

The brief is as follows: In this example, compareTo returns positive 8, because the second letter of "Ada" comes before the second letter of "Alan" by 8 letters

But we do not see what the two strings that are being compared to are. It would be easier to follow if it was added too.

**Comment by damithc** [comment]
Good point @Bencotti 
I've refined the explanation.
