### ISSUE TITLE
Are our iP graded on a weekly basis?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#15]
Understood from the previous issue [here](https://github.com/nus-cs2113-AY1920S2/forum/issues/9) that we are to push our work to our GitHub repo starting from Week 3. 
However, are we going to get grade/feedback for our iP every week?

**Comment by damithc** [comment]
It's not _graded_ every week but making weekly progress is [an iP grading criterion](https://nus-cs2113-ay1920s2.github.io/website/admin/ip-grading.html#ip-grading). You should push your code frequently so that our bots can monitor your progress.

**Comment by Zhilin-Huang** [comment]
Noted! Also, for the exercises on repl.it every week, will we get frequent grade/feedback on this component? Or is it sufficient that we make sure we submit solutions that pass all the test cases?

**Comment by damithc** [comment]
It's fine as long as you pass the tests. You can also view the model solution after you submit which should help you ways to improve your code.

**Comment by Zhilin-Huang** [comment]
Thanks for the clarification!
