### ISSUE TITLE
Emulating destructor in C++

### ISSUE THREAD

**Issue by MeLoveCarbs** [nus-cs2113-AY1920S2/forum#16]
I understand that Java uses garbage collector and thus, there is no need for destructor methods. But without destructors, how can I know the total number of objects within a class during runtime? For eg, if I can only increment the number of objects in the constructor method but not decrement it under the destructor method, wouldn't the total count be inaccurate if an unreferenced object gets garbage collected without decrementing total object count explicitly?

**Comment by A11riseforme** [comment]
Maybe you can define a finalize method? https://javaconceptoftheday.com/garbage-collection-finalize-method-java/

**Comment by MeLoveCarbs** [comment]
From what i understand, finalize method only cleans unreferenced objects when called, but my issue is that i want to have a static class member variable that has the total count of objects in runtime, and i want to decrement it whenever unreferenced object gets garbage collected, and increment it whenever a new object is created.

**Comment by A11riseforme** [comment]
I think that is what you need. finalize() is called before the garbage collector tries to release the unreferenced object memory, and you can put the decrement of the static class variable in the finalize() method. But when the garbage collector works is totally up to jvm, even you reference an object to null, the JVM may start garbage collection only when it runs out of memory. so the finalize method may not be called throughout the entire programme running time.
Correct me if I am wrong.

**Comment by MeLoveCarbs** [comment]
Oh okay, thanks for explaining! Closing this issue now!

**Comment by damithc** [comment]
Thanks for the inputs @A11riseforme :+1:

**Comment by damithc** [comment]
@MeLoveCarbs In most cases, it is advisable to structure your program logic such that you don't _need to_ keep track of how many un-referenced objects of a certain kind are in the memory i.e., the program should only care about objects that are being referenced. If an object is no longer referenced, it should not affect the state of the program anymore. That's the price you pay for the convenience of automatic garbage collection.
