### ISSUE TITLE
Tutor's email addresses?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#17]
Understood that the tutors for each tutorial group are listed in the module website. But where could we get the email addresses of our tutors?

Any help is appreciated!

**Comment by A11riseforme** [comment]
https://nus-cs2113-ay1920s2.github.io/website/admin/instructors.html

**Comment by Zhilin-Huang** [comment]
> https://nus-cs2113-ay1920s2.github.io/website/admin/instructors.html

Thank you!

**Comment by damithc** [comment]
I've added a link to the relevant page, for good measure.

![image](https://user-images.githubusercontent.com/1673303/73336532-06dacf00-42ad-11ea-9117-4e9719f07ad4.png)
