### ISSUE TITLE
(A-TextUiTesting) Unicode characters in txt files

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#18]
When redirecting output from the console into a txt file, I find that I am unable to represent Unicode characters properly. This problem occurs since in the Duke chatbot, stylized ticks and crosses are used to indicate the status of completion for different tasks.

Every time when I try to run the batch script, I get something like this:
***** ACTUAL.TXT
Got it. I've added this task:
  [E][?] project meeting (at: Mon 2-4pm)
Now you have 3 tasks in the list.
***** EXPECTED.TXT
Got it. I've added this task:
  [E][Γ£ÿ] project meeting (at: Mon 2-4pm)
Now you have 3 tasks in the list.
*****
Any stylized symbols get transformed into a "?" the moment I try to put them in a txt file. May I know if there is a workaround for this issue?

**Comment by damithc** [comment]
Let's see if anyone can offer a solution. In the meantime, you can switch to using regular characters. e.g.,
`[/]` for done and `[ ]` for not done.

**Comment by chaosInTheWild** [comment]
Just found a solution, I basically added the "-Dfile.encoding=UTF8" into the java command in the batch script.
java -Dfile.encoding=UTF8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT
Referenced from this website: http://hints.macworld.com/article.php?story=20050208053951714

**Comment by damithc** [comment]
> Just found a solution, I basically added the "-Dfile.encoding=UTF8" into the java command in the batch script.

Nice 👍
