### ISSUE TITLE
SourceTree: Can't commit changes because of "Binary file"

### ISSUE THREAD

**Issue by tzzzening** [nus-cs2113-AY1920S2/forum#19]
Hello,

I tried to commit some changes in SourceTree after editing. However, it says "No changes in this file have been detected, or it is a binary file".

I tried to google and they suggested changing the Size Limit in settings but it still didn't work.

I'm not sure what is the issue

**Comment by damithc** [comment]
Can you give a full screenshot of your SourceTree, clearly showing all the staged files?

**Comment by tzzzening** [comment]
![2020-01-31 (2)](https://user-images.githubusercontent.com/59819947/73521675-931dfb00-4441-11ea-9e3a-208e26318ec4.png)

I'm not sure if this counts. Because when I click on the file to be staged, no preview comes out

**Comment by damithc** [comment]
Looks like you haven't staged the file. Click on `Duke.java`file  (in the `Unstaged files` panel) and then click `Stage selected` button.
Also, you might want to watch the Lecture 1 webcast which has a demo of this operation.

**Comment by tzzzening** [comment]
Okay thank you Prof

**Comment by damithc** [comment]
Don't forget to close this issue if the problem has been resolved.
