### ISSUE TITLE
Tags on GitHub

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#20]
I have unintentionally removed one of my tags on the commits in Github and I tried to undo that removal by re-pushing my latest commit (with all tags pushed). Now, for my latest commit (first picture below) it shows its own tag, whereas for my first commit (second picture below), it shows all the tags which I have ever included in a commit.
![image](https://user-images.githubusercontent.com/42376931/73540657-7c8c9980-446b-11ea-829a-5295c733a00a.png)

![image](https://user-images.githubusercontent.com/42376931/73540767-be1d4480-446b-11ea-86fa-b31ecaf31788.png)

Can I clarify if this is what I am supposed to see if I have tagged the commits correctly?

**Comment by Zhilin-Huang** [comment]
Not sure what's the problem with the second screenshot, but from your GitHub repo I see that your tags are attached to different commits instead of the first commit: [https://github.com/kokjoon97/duke/releases](https://github.com/kokjoon97/duke/releases)

**Comment by chaosInTheWild** [comment]
I wonder if it is a feature of GitHub for commits to show their own tag and tags of commits that come after them, though I could imagine that might make it hard to track which tag is for which commit specifically

**Comment by damithc** [comment]
GitHub does some weird stuff with tags e.g., treating tags as releases
It's fine as long as tags show up correctly in your local repo e.g., when using SourceTree

**Comment by chaosInTheWild** [comment]
Okay thank you for clarifying prof!
