### ISSUE TITLE
Problem when importing contacts project to Intellij

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#23]
I tried to import contacts project mentioned in Lecture 3, but the IDE only recognize "src\main\java" as source directory so project only includes files under this directory after import. However the project still need files from "text-ui-test" or something. How can I fix this problem? Any help would be appreciated!

**Comment by damithc** [comment]
You can change the view to 'Project Files' instead of 'Project' to see non-java files.
![image](https://user-images.githubusercontent.com/1673303/73646475-7c330f00-46b4-11ea-8280-8720513e7b99.png)

**Comment by SibingWu** [comment]
> You can change the view to 'Project Files' instead of 'Project' to see non-java files.

Thanks that help! However I wonder when you demo during lecture, it seems that it showed all files including non-java files with "Project", why this is so?

**Comment by SibingWu** [comment]
Also I am not sure what is wrong here, but there seems to ACTUAL.txt
![image](https://user-images.githubusercontent.com/49228945/73646739-067b7300-46b5-11ea-8c4d-868995dc3a04.png)

**Comment by rdimaio** [comment]
> Also I am not sure what is wrong here, but there seems to ACTUAL.txt
> ![image](https://user-images.githubusercontent.com/49228945/73646739-067b7300-46b5-11ea-8c4d-868995dc3a04.png)

ACTUAL.TXT is generated by the script and contains the actual output from the program, so it doesn't need to be present before the script runs. If ACTUAL.TXT is present, the script deletes it before compiling and running the program again (e.g. in the .bat script on line 7):

`del ACTUAL.TXT`

**Comment by SibingWu** [comment]
> Also I am not sure what is wrong here, but there seems to ACTUAL.txt
> 
> 
> ACTUAL.TXT is generated by the script and contains the actual output from the program, so it doesn't need to be present before the script runs. If ACTUAL.TXT is present, the script deletes it before compiling and running the program again (e.g. in the .bat script on line 7):
> del ACTUAL.TXT

OK thx so much! Problem fixed!

**Comment by damithc** [comment]
Thanks for the help @rdimaio 
Go ahead and close this issue if the problem is resolved @SibingWu

**Comment by SibingWu** [comment]
> Thanks for the help @rdimaio
> Go ahead and close this issue if the problem is resolved @SibingWu

Professor I am still wondering why when you demo during lecture, it seems that it showed all files including non-java files with "Project" instead of Project Files

**Comment by damithc** [comment]
> Professor I am still wondering why when you demo during lecture, it seems that it showed all files including non-java files with "Project" instead of Project Files

I suspect  that earlier (before the lecture), I must have set some setting in Intellij to make those files visible by default, although I can't remember exactly what though.

**Comment by SibingWu** [comment]
> Professor I am still wondering why when you demo during lecture, it seems that it showed all files including non-java files with "Project" instead of Project Files
> 
> I suspect  that earlier (before the lecture), I must have set some setting in Intellij to make those files visible by default, although I can't remember exactly what though.

OK, thank you so much for your help!
