### ISSUE TITLE
IP: Cannot show tick icon properly

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#24]
For IP, when generating the ACTUAL.txt file, it seems that tick icon cannot be shown properly. I wonder how I can fix it? Any help would be appreciated!

![image](https://user-images.githubusercontent.com/49228945/73653301-d8e9f600-46c3-11ea-8a32-1323171e85e6.png)

**Comment by A11riseforme** [comment]
replace line 18 in runtest.bat to 
`java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT`

**Comment by SibingWu** [comment]
> replace line 18 in runtest.bat to
> java -Dfile.encoding=UTF-8 -classpath ..\bin Duke < input.txt > ACTUAL.TXT

Thank you so much for your help! Problem fixed!
