### ISSUE TITLE
Inquiry on Coding Style of main function

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#25]
I wonder for good coding style, it is better to put the function definition before main function/where it is called or after?

**Comment by damithc** [comment]
As that aspect is not specified in the coding standard, you are free to choose your own, but apply in consistently throughout the code base.

**Comment by SibingWu** [comment]
> As that aspect is not specified in the coding standard, you are free to choose your own, but apply in consistently throughout the code base.

Thank you so much! Confusion clarified.
