### ISSUE TITLE
Broken links in Week 6 e-learning instructions

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#26]
It seems that the links to the textbook chapters required for week 6 [e-learning](https://nus-cs2113-ay1920s2.github.io/website/schedule/week6/index.html
) are broken.

I get a page not found error when clicking on any of the 3 links: e.g. [https://nus-cs2113-ay1920s2.github.io/website/schedule/week6/se-book-adapted/chapters/requirements.html](https://nus-cs2113-ay1920s2.github.io/website/schedule/week6/se-book-adapted/chapters/requirements.html)

**Comment by damithc** [comment]
Thanks for the bug report @Zhilin-Huang 
Fixed
