### ISSUE TITLE
Inquiry on Merge Conflict

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#27]
I wonder what the three markers mean?

![image](https://user-images.githubusercontent.com/49228945/74320200-28fb4380-4dbb-11ea-9bfb-50a9d3641af6.png)

**Comment by damithc** [comment]
There is a slightly longer explanation in the textbook, quoted below:
![image](https://user-images.githubusercontent.com/1673303/74321219-df135d00-4dbc-11ea-8e46-0f16cdf64580.png)

It shows what each branch is trying to add to that location of the file.
