### ISSUE TITLE
Duke output

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#28]
Can I check if it is a must to follow the output of Duke exactly as given in the iP tasks? Is it acceptable if we vary the format of the output but still achieve the same functions? 

For example, even after I have fixed writing of UTF-8 characters into txt files using 
-Dfile.encoding=UTF8, I am still having problems with the command prompt not displaying UTF-8 characters when I tried running the JAR file which I created. I have tried changing the code page to 65001 but it does not seem to work and most solutions I have found suggested editing the registry which seems pretty risky.

**Comment by Zhilin-Huang** [comment]
Based on how I understand the requirements, I think we are allowed to customize the output of our bot as we see fit

**Comment by damithc** [comment]
> Based on how I understand the requirements, I think we are allowed to customize the output of our bot as we see fit

@Zhilin-Huang is correct. In fact you are strongly encouraged to.
![image](https://user-images.githubusercontent.com/1673303/74336307-f5c7ad00-4dd8-11ea-8645-5ad8ce60391d.png)

**Comment by chaosInTheWild** [comment]
Okay thank you for clarifying!
