### ISSUE TITLE
Model answer for post-lecture quizzes

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#29]
I noticed that we do not get direct feedback on whether or not the answers we submit for post-lecture quizzes on LumiNUS are correct. Will we get the model answers after the deadline?

**Comment by damithc** [comment]
Yes @Zhilin-Huang answers will be released after the deadline.

**Comment by Zhilin-Huang** [comment]
Thanks Prof!
