### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by A11riseforme** [nus-cs2113-AY1920S2/forum#3]
https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/uml.html#associations
https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/oop.html#classes
to **indication** the three priority levels -> to **indicate** the three priority levels

https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/oop.html#implementing-multiplicity
without having a **direction** association with it -> without having a **direct** association with it

https://nus-cs2113-ay1920s2.github.io/website/schedule/week4/topics.html#paradigms-oop-inheritance-what
**woment** -> **women**

https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/designFundamentals.html#cohesion
because the code **realated** to that change -> because the code **related** to that change

https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/codeQuality.html#intermediate
it has no value on matter how fast/efficient it **it**. -> it has no value on matter how fast/efficient it **is**.

https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html#git-and-github
Git will now show ignored **fiels** as ‘unstaged modifications’  -> Git will now show ignored **files** as ‘unstaged modifications’ 
Note that the URL of the Github project is different **form** the URL -> Note that the URL of the Github project is different **from** the URL you 

https://nus-cs2113-ay1920s2.github.io/website/se-book-adapted/chapters/gitAndGithub.html#git-and-github
Creating Pull **Requsts** (PRs) is needed -> Creating Pull **Requests** (PRs) is needed

**Comment by damithc** [comment]
Thanks for the many bug reports @A11riseforme 
Fixed
