### ISSUE TITLE
Help with 'gradlew run' command

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#31]
After I merged the branch `gradle` to my `master` branch, I'm unable to run `gradlew run` as it gives `zsh: command not found: gradlew` error. But I'm able to run `./gradlew run`.

Is it okay to just run `./gradlew run`? And why is it failing to execute `gradlew run`?

Any help is appreciated!

**Comment by damithc** [comment]
Yes, they are the same @Zhilin-Huang 
Also, you don't actually need gradle for the iP.

**Comment by Zhilin-Huang** [comment]
I see! But it seems that `A-Gradle` is an increment under `A-Jar` for Week 6 iP tasks [here](https://nus-cs2113-ay1920s2.github.io/website/schedule/week6/project.html)?

**Comment by damithc** [comment]
> I see! But it seems that `A-Gradle` is an increment under `A-Jar` for Week 6 iP tasks [here](https://nus-cs2113-ay1920s2.github.io/website/schedule/week6/project.html)?

It's optional @Zhilin-Huang (it says `If you are using ...`)

**Comment by Zhilin-Huang** [comment]
Thanks for the clarification 👍
