### ISSUE TITLE
iP Demo in Week 6 Tutorial

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#32]
Is the iP demo in next week's tutorial graded as part of our iP mark?
The iP grading page is [here](https://nus-cs2113-ay1920s2.github.io/website/admin/ip-grading.html#ip-grading) but I didn't find anything related to the demo.

**Comment by damithc** [comment]
Not graded @Zhilin-Huang. It's just for us to ensure you have achieved sufficient progress as we are now nearing the final submission.

**Comment by Zhilin-Huang** [comment]
Thanks for the clarification!
