### ISSUE TITLE
Not able to read file properly via relative path

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#33]
I tried to read the txt file using relative path, however it always said "file not exists"; if I changed it to absolute path, then it can be read. I wonder what is wrong with it?

private static String filePath = ".." + File.separator + ".." + File.separator + "data" + File.separator + "duke.txt";

![image](https://user-images.githubusercontent.com/49228945/74545832-82fb3500-4f84-11ea-97da-b6dc15b1e359.png)

**Comment by damithc** [comment]
One thing you can try is to print the 'current working directory' from your code. That should tell you what directory is your path 'relative to'. It may not be the location of the java file.

**Comment by SibingWu** [comment]
> One thing you can try is to print the 'current working directory' from your code. That should tell you what directory is your path 'relative to'. It may not be the location of the java file.

Thank you so much! Problem fixed!
