### ISSUE TITLE
Data files can't be found when running JAR

### ISSUE THREAD

**Issue by JeremyTakigawa** [nus-cs2113-AY1920S2/forum#35]
I added the file duke.txt in /data and had
 File file = new File("data/duke.txt");
in my code.
But when packaged as JAR, 
"Exception in thread "main" java.io.FileNotFoundException: data/duke.txt (No such file or directory)"
How should I package data folder into JAR.

**Comment by Jeremy733** [comment]
I got it fixed

**Comment by JeremyTakigawa** [comment]
I got the JAR file running however it still does not save. Therefore if you shut down and rerun the JAR file, you will start with an empty file.

**Comment by JosephLimWeiJie** [comment]
Hi, you might want to check your save function and see if it writes to the same file path as the one you use for your load function

**Comment by damithc** [comment]
@Jeremy733 It's easier for others to help if you push your code to a branch and share the link to your branch here.

**Comment by AceCentury** [comment]
A possibility could be that your writes are buffered and not actually being written.

As what prof has said, giving a sample branch for us to look at would allow us to take a peek into your code.

**Comment by JTWang2000** [comment]
I am not sure if this solution is okay. I add a folder called "data" which is in the same directory as the jar file, then the jar file works.

**Comment by JeremyTakigawa** [comment]
@JTWang2000 This is also my temporary fix but I believe we should only be distributing JAR files when releasing it

**Comment by damithc** [comment]
> I am not sure if this solution is okay. I add a folder called "data" which is in the same directory as the jar file, then the jar file works.

@JTWang2000 If you take this approach, the folder should be created by the code (i.e., don't expect the user to create a folder manually). In your code, check if the folder `data` exists, and create the folder if it doesn't.

**Comment by SibingWu** [comment]
I think you may run the jar file in a improper directory. Maybe you can try this:
1. cd to the directory of "duke" project
2. then "java -jar xxxx.jar"
I think it will be fixed

![image](https://user-images.githubusercontent.com/49228945/74663513-dd8bcf80-51d6-11ea-8979-b44dcf101933.png)

Since that the path we used to find txt file is a relative path, so it is very important that which directory we are relative to (just guess

**Comment by damithc** [comment]
> I think you may run the jar file in a improper directory. Maybe you can try this:
> 
> 1. cd to the directory of "duke" project
> 2. then "java -jar xxxx.jar"
>    I think it will be fixed
> 
> ![image](https://user-images.githubusercontent.com/49228945/74663513-dd8bcf80-51d6-11ea-8979-b44dcf101933.png)
> 
> Since that the path we used to find txt file is a relative path, so it is very important that which directory we are relative to (just guess

It should work in the following scenario.
1. Copy the jar to **any empty folder**
1. CD into that folder
1. run `java -jar Duke.jar`

If it works only from your duke project root folder, most likely your code doesn't handle the case where the `data` folder does not exist when the user runs the jar file for the first time.

**Comment by JeremyTakigawa** [comment]
![image](https://user-images.githubusercontent.com/37642497/74666151-f8ad0e00-51db-11ea-9ad9-60bb9839c270.png)

**Comment by JeremyTakigawa** [comment]
I have adopted the solution of creating a new file if it doesn't exist. As long as the user of the jar doesn't move around files into different folders I think it should work.

**Comment by damithc** [comment]
> I have adopted the solution of creating a new file if it doesn't exist. As long as the user of the jar doesn't move around files into different folders I think it should work.

Nice. Based on your code, it seems the app carries on (after printing the stack trace) even if the file creation fails. Perhaps it's better to terminate if the file creation failed?

**Comment by JeremyTakigawa** [comment]
@damithc Thank you for your advice, I'm refactoring the code to make it works better

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/74667519-65c1a300-51de-11ea-84d7-9aec1df5e2e9.png)
I have tried creating a new file when there is no duke.txt However, it still does not work. I suppose that the jar cannot find the data folder?

**Comment by JeremyTakigawa** [comment]
@JTWang2000 You need to check if data folder exists or not or to make life easier just cdo 
File f = new File(duke.txt)

**Comment by AceCentury** [comment]
@JTWang2000 Something to consider: What would happen after your code catches the `FIleNotFoundException` ? Will it continue to run your `while` loop?

**Comment by JTWang2000** [comment]
> @JTWang2000 Something to consider: What would happen after your code catches the `FIleNotFoundException` ? Will it continue to run your `while` loop?

I suppose that it will not run the while loop? It means there is no such file so it will create a duke.txt file. However, it cannot find the data folder so it cannot create?

**Comment by JTWang2000** [comment]
@Jeremy733 yeah i tried to make it File f = new File(duke.txt). OMG it works! But is that okay that we do not a data foler?

**Comment by JeremyTakigawa** [comment]
@JTWang2000 From what I understand as long as you can save the file locally it's fine

**Comment by damithc** [comment]
> @Jeremy733 yeah i tried to make it File f = new File(duke.txt). OMG it works! But is that okay that we do not a data foler?

Having a data folder is not a requirement. But it's useful to learn how to put the data in a specific folder as you can't always get away with creating all files in the root folder :-)

**Comment by AceCentury** [comment]
> > @JTWang2000 Something to consider: What would happen after your code catches the `FIleNotFoundException` ? Will it continue to run your `while` loop?
> 
> I suppose that it will not run the while loop? It means there is no such file so it will create a duke.txt file. However, it cannot find the data folder so it cannot create?

Yes, you also need to check for the existence of the directory. 

The question about the `while` loop was just me trying to check your understanding.

**Comment by brandoncjh** [comment]
@damithc I feel it could become an issue if I create a duke.txt everytime I run the .jar file in a new directory without keeping track 😆 Is there anyway to redirect to the original duke.txt, maybe create a shortcut/symlink to data/duke.txt?

**Comment by damithc** [comment]
> @damithc I feel it could become an issue if I create a duke.txt everytime I run the .jar file in a new directory without keeping track 😆 Is there anyway to redirect to the original duke.txt, maybe create a shortcut/symlink to data/duke.txt?

Why is it an issue? Moving the jar file to a new folder is usually done only once i.e., when running the app for the first time. If the user wants to move it to a different location later, they can move the entire folder (assuming the data files created by duke are also inside the same folder).
