### ISSUE TITLE
IP: Cannot show tick icon properly both in terminal and ACTUAL.txt

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#36]
Hi, even in the terminal, my tick icon cannot display properly. I am not sure if that is because the encoding of the project has something wrong. 
![image](https://user-images.githubusercontent.com/49268567/74663466-c77e0f00-51d6-11ea-8fc1-8c7cf0b99d21.png)

**Comment by damithc** [comment]
If you mean the intellij terminal, it's same as the normal OS terminal, just shown inside Intellij.
Don't worry about this issue. Just use a regular character instead of tick. e.g., `[/]`

**Comment by JTWang2000** [comment]
Thank you for your reply. Then i just use the a regular character.
