### ISSUE TITLE
[Text-ui-test] Can not find /data/duke.txt

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#37]
When I am running the text-ui-test after creating the Level-7, it cannot find the duke.txt. May I ask what to deal with? Do we need to add some lines in the runtest.bat?

**Comment by damithc** [comment]
Anyone else who managed to keep text-ui-test working after Level-7 would like to share how they did it?

**Comment by JosephLimWeiJie** [comment]
![Capture](https://user-images.githubusercontent.com/59989652/74665910-82101080-51db-11ea-997b-cfa34c89016f.PNG)

Well you may want to add the data/duke.txt into the runtest.bat. This is what I've got.

**Comment by damithc** [comment]
A general tip: if you expects the data file to be in specific folder e.g., `./data/`, your code must check if the folder exists and create it if it doesn't. If your code doesn't have that, your text ui tests could fail too.

**Comment by JTWang2000** [comment]
> A general tip: if you expects the data file to be in specific folder e.g., `./data/`, your code must check if the folder exists and create it if it doesn't. If your code doesn't have that, your text ui tests could fail too.

yep. I find that even if i add the data directory in the runtest.bat, still got similar error as the jar file which is cannot find data directory.

**Comment by wangqinNick** [comment]
Do you mean when you run the jar file, the initial task list is not loaded because can not find the file?

**Comment by JTWang2000** [comment]
> Do you mean when you run the jar file, the initial task list is not loaded because can not find the file?
Sorry for answering so late. Yes. I think because there is no data folder.

**Comment by kcubey** [comment]
If when you run the jar file alone, you're getting errors because there is no data folder, that probably means that you need to add code to your program that will create folder(s) if they do not already exist

**Comment by dejunnn** [comment]
Im actually also having issues with saving the file. It only works if I use the absolute pathway but that will cause errors when using the jar file. Tried many variations but none of them is working :(

**Comment by damithc** [comment]
> Im actually also having issues with saving the file. It only works if I use the absolute pathway but that will cause errors when using the jar file. Tried many variations but none of them is working :(

@dejunnn
Share your code and error message you get.
Also, you can check [the code of a few others](https://nus-cs2113-ay1920s2.github.io/ip-dashboard) to see how they have done it.

**Comment by dejunnn** [comment]
This was what I used previously. I actually redid a lot of my code so it looks different now.
The brute force rewriting of the file was just a temporary measure as I was more focused on getting the reading and saving parts to work.

![image](https://user-images.githubusercontent.com/51941453/75508023-b5457180-5a1d-11ea-8386-3b1ce0db9562.png)
![image](https://user-images.githubusercontent.com/51941453/75508087-e756d380-5a1d-11ea-9fa4-2f7311941b8d.png)

**Comment by brandoncjh** [comment]
createNewFile will try to create the file according to the path you have specified in the File object. If the directory your jar file is located in does not have a subfolder path "src/main/java/data", it will throw an error. So maybe you could try to see how you can rectify this error.

Note: the jar file should be run in an empty directory

**Comment by JTWang2000** [comment]
My understanding for this problem is that: Previously, there is no data/duke.txt. When we first run duke, it will be created. Therefore, we may need to add code to create a data folder and a duke.txt. This may solve both jar problem and test-ui problem?

**Comment by dejunnn** [comment]
The one above is an absolute path but that won't work when using a jar file, still trying to figure out the relative path. Though honestly not exactly sure how it would work in that case.

**Comment by brandoncjh** [comment]
Relative path points to the path of the file relative to your current location/directory.  So say if I'm in "./src/main" and I want to access "./src/main/java/duke/duke.txt", the relative path would be "java/duke/duke.txt". 

For the jar case, you could run it in an empty directory eg "test". So for this example, the jar file will try to locate the saved tasklist file in whatever relative path you specified ie "test/\<relativepath\>"

**Comment by JTWang2000** [comment]
I have added a test when loading the duke.txt file and will create a data folder. Then, even if I do not add the path in runtest.bat, it still works. It is just that every time when a runtest, I need to delete the data folder to ensure the actual and expected txt matches. 
![image](https://user-images.githubusercontent.com/49268567/75603454-696ff680-5b09-11ea-83f4-64d3e1c276ae.png)
Thanks for those who have helped me.
