### ISSUE TITLE
Scripts ignoring untagged commits?

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#39]
I made a costly mistake by creating a branch from one of my branches instead of from the master branch. As a result, when I created the PRs and tried to merge, the results were disastrous.

I have then tried to delete the changes manually and make a new commit to "undo" the change since I don't think it is possible to revert commits on GitHub. After this, I did the merging of the PRs correctly and also tagged the merge commits. 

Will the scripts only focus on the commits that are tagged and ignore the erratic commits that I have made to the fork?

**Comment by damithc** [comment]
It's good to make mistakes like that. Just a rite of passage in learning git.
Which script (i.e., the script doing what)? For example, the script checking weekly iP progress will consider all commits as long as they have been merged to the master branch.
Do you want those commits to be counted, or don't want them to be counted?

**Comment by chaosInTheWild** [comment]
I was just wondering if the scripts would detect the erratic commits and if there are any penalties for those commits

**Comment by damithc** [comment]
> I was just wondering if the scripts would detect the erratic commits and if there are any penalties for those commits

No penalties. Not to worry.

**Comment by chaosInTheWild** [comment]
Okay thank you for clarifying prof!
