### ISSUE TITLE
Possible bug in Week 2: Ex 2 Compare Names??

### ISSUE THREAD

**Issue by yukilite** [nus-cs2113-AY1920S2/forum#4]
Keeps throwing either the error of class Main cannot be found.
or 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at Main.main(Main.java:3).

**Comment by thanhduc2000** [comment]
Then may be you have accessed out of bound index in array i guess

**Comment by yukilite** [comment]
mm I see, where did I go wrong here?

class WordComparator {
  public static void main(String[] args) {
      if (args.length > 0) {
      String x = args[0];
      String y = args[1];
      System.out.println("Words given: " + x + ", " + y);
      boolean isSame = y.equals(x);
      System.out.println("They are the same: "+ isSame);
    }
  }
}

**Comment by damithc** [comment]
Tip: GitHub issue tracker supports markdown syntax. 
![image](https://user-images.githubusercontent.com/1673303/72438137-2cf96d00-37df-11ea-8371-a064f65e0d0d.png)


will show as:
```java
public static void main(String[] args) {...}
```

more info https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by damithc** [comment]
> Keeps throwing either the error of class Main cannot be found.

This exercise is meant to be done on your computer. When you are happy with the code, copy-paste it into repl. I'll add that instruction.

On a separate note, `args.length > 0` condition is satisfied even if there is only one argument.

**Comment by terrytay** [comment]
Filename and class name should be the same. You can try doing a copy of it on your desktop and save the file as WordComparator.java and try running it. If it works, you can just paste the code and submit. Hope it helps!

https://netjs.blogspot.com/2015/04/why-file-name-and-class-name-same-in-java.html
