### ISSUE TITLE
Edits done in IntelliJ does not show when I run the code

### ISSUE THREAD

**Issue by tzzzening** [nus-cs2113-AY1920S2/forum#40]
Hello, I'm not sure when this problem started, but now any edits that I make on IntelliJ are not reflected when I run the code. I have tried printing strings when I greet the user to ensure that this is not caused by any error in logic, but it did not work.

Did anyone face the same problem?

**Comment by rdimaio** [comment]
Are you building the project before running it again? Normally if you made edits and then pressed run it should automatically build it before running, but maybe this feature could have been disabled in the settings. Have you tried going to Build -> Clean build?

**Comment by damithc** [comment]
@chengTzeNing solved?
If not, delete the .idea folder and import the project again to see if that helps.

**Comment by tzzzening** [comment]
> Are you building the project before running it again? Normally if you made edits and then pressed run it should automatically build it before running, but maybe this feature could have been disabled in the settings. Have you tried going to Build -> Clean build?

Thanks for your suggestion, but there's no "clean Build" option under "Build" though

**Comment by wangqinNick** [comment]
> > Are you building the project before running it again? Normally if you made edits and then pressed run it should automatically build it before running, but maybe this feature could have been disabled in the settings. Have you tried going to Build -> Clean build?
> 
> Thanks for your suggestion, but there's no "clean Build" option under "Build" though

Did you implement gradle? Gradle can help build and also can clean build.

**Comment by damithc** [comment]
> Did you implement gradle? Gradle can help build and also can clean build.

Best to leave out gradle as it isn't part of the iP requirements. :-) 
This problem should be solvable without gradle.

> Thanks for your suggestion, but there's no "clean Build" option under "Build" though

Use the `Rebuild` option

**Comment by tzzzening** [comment]
Thank you for all the suggestions! I have somewhat solved the issue.
