### ISSUE TITLE
Unknown error when doing A-oop

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#41]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

```java
String value = "Some code here"
```

When i am refactoring the code, there are some unknown errors displayed on Intellij.
![image](https://user-images.githubusercontent.com/49268567/75332310-215d9380-58bf-11ea-8546-05aa011dbab3.png)
All newly created class suffer from this errors. I have searched and tried to change encoding. However, still cannot really see the errors. 

:bulb: You can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format your text

**Comment by A11riseforme** [comment]
can you check if `；` is the chinese character?...

**Comment by JTWang2000** [comment]
> can you check if `；` is the chinese character?...

Have tried. If it is the Chinese character, then the display will be:
![image](https://user-images.githubusercontent.com/49268567/75332656-b791b980-58bf-11ea-94c0-08ffe841c023.png)
So it should be the English character

**Comment by damithc** [comment]
You can copy paste some code from the problematic files into a tool like [this one](https://www.soscisurvey.de/tools/view-chars.php) to see if there are some hidden characters in the code.
Also check if your other Intellij java projects suffer from this problem. If they don't, you can try reimporting this project.

**Comment by JTWang2000** [comment]
> You can copy paste some code from the problematic files into a tool like [this one](https://www.soscisurvey.de/tools/view-chars.php) to see if there are some hidden characters in the code.
> Also check if your other Intellij java projects suffer from this problem. If they don't, you can try reimporting this project.

Thank you for your reply. 
After pasting the code to the website:
![image](https://user-images.githubusercontent.com/49268567/75333902-e741c100-58c1-11ea-90e6-07a216437e4f.png)
I suppose that there is no hidden characters?

I tried the circus class we used to use during lecture. When i am creating class and package, it works fine. Then, I tried to reimport this project, still have the same problem. 

I tried to change the console to UTF -16 to try to see if the strange "characters" are chinese character:
![image](https://user-images.githubusercontent.com/49268567/75334071-31c33d80-58c2-11ea-8dc0-1218c3958bba.png)
Also failed. Very confusing.

**Comment by JTWang2000** [comment]
![image](https://user-images.githubusercontent.com/49268567/75334566-0db42c00-58c3-11ea-8b69-6a3af795e031.png)
I tried to rewrite the: package duke.command;
a new error appears. 
I suppose that maybe my encoding of all the files are wrong?

Then, i check the setting which displays:
![image](https://user-images.githubusercontent.com/49268567/75334725-4eac4080-58c3-11ea-8adb-cc8d25043dd4.png)

**Comment by A11riseforme** [comment]
GBK is the encoding for Chinese characters... and 0xBF is part of the BOM header. I suspect that you edited the file using the windows notepad before.... you can copy the content of the file, paste into notepad, delete this file, create a new one, then paste it back and try if error is still there.

actually the IntelliJ is providing a `Remove BOM` function, right click on the file and select `Remove BOM`

**Comment by JTWang2000** [comment]
I tried the Remove BOM function. It works! Thank you so much.

**Comment by damithc** [comment]
> actually the IntelliJ is providing a `Remove BOM` function, right click on the file and select `Remove BOM`

Nice! Thanks for the help @A11riseforme 👍

**Comment by A11riseforme** [comment]
No problem, glad I can help.
