### ISSUE TITLE
Delete a commit in github

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#43]
![image](https://user-images.githubusercontent.com/49268567/75419896-ce90e400-5971-11ea-9081-1fc2270e0ff2.png)
Is it okay to delete a commit on github by:
git reset --hard HEAD^
git push origin +branchName --force

**Comment by Zhilin-Huang** [comment]
If you are very sure that you want to delete that commit, then it should be fine to do so.

**Comment by damithc** [comment]
For the iP, should be fine. Not advisable if the repo is shared by others, so try to avoid doing it in the tP.

**Comment by JTWang2000** [comment]
@Zhilin-Huang Sure. Thanks. This command works
@damithc  Thank you for your advice.
