### ISSUE TITLE
Wrong tagging and unable to change it

### ISSUE THREAD

**Issue by Shannonwje** [nus-cs2113-AY1920S2/forum#44]
Hi, I did my A-MoreOOP but I realised I missed out one part of it after I pushed the incomplete commit with the tag A-MoreOOP. Now after I finished my A-MoreOOP increment, I tried to push that commit with the same tag but it told me that I couldn't do so due to a conflict.

I tried to change the old tag name, and tried to delete the tag on github but it looks like nothing changed, even though now I can push the tag on my completed commit. Unsure if I did this retagging correctly, hope it doesn't affect my grades :(

**Comment by damithc** [comment]
It's fine as long as the expected tag is in the repo and the work has been done @Shannonwje 
It's OK if the tag is in a different commit.

**Comment by Shannonwje** [comment]
Ok thank you Sir!!!
