### ISSUE TITLE
A-JavaDoc not in a branch

### ISSUE THREAD

**Issue by Shannonwje** [nus-cs2113-AY1920S2/forum#45]
Hi I've been adding the headers and the comments for my code for a while and so throughout my code in all my branches, majority of my code already has headers so I won't be to do my A-Javadoc in a separate branch and merging it into my master. 

How should I proceed? Please advise, thank you :)

**Comment by damithc** [comment]
It's not a problem but keep in mind that it will still show up as a 'missing' item in the dashboard. If you want to avoid that, you can use a branch even if it doesn't contain much code. I'm sure you can find _something_ to improve in your javadoc comments even if you have been adding them all along (kudos for doing that BTW)

**Comment by Shannonwje** [comment]
Ok! Have created a branch for it and did some minor javadoc comments in it. Thank you!!
