### ISSUE TITLE
Edit does not reflect when doing test-ui-test

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#46]
I modified the code and the demo looks like this.
![image](https://user-images.githubusercontent.com/49228945/75507568-7236ce80-5a1c-11ea-9372-5f6efa1d91fc.png)

However, when I ran test-ui-test, it told me that there was difference.

![image](https://user-images.githubusercontent.com/49228945/75507602-8a0e5280-5a1c-11ea-8c1c-6cf9307787aa.png)

I wonder why this is so and how I can make changes

**Comment by JTWang2000** [comment]
Maybe you have added some new package and you forgot to put the path?

**Comment by SibingWu** [comment]
> Maybe you have added some new package and you forgot to put the path?

if this is so, the idea will just report error for not finding the classes

**Comment by brandoncjh** [comment]
I think she is referring to your runtest.bat. It may compile and run as normal in the terminal but shows this response because the new classes have not been included in the batch script.

**Comment by SibingWu** [comment]
> I think she is referring to your runtest.bat. It may compile and run as normal in the terminal but shows this response because the new classes have not been included in the batch script.

I understand, and I have tried; if the batch script does not include the new package, it will report the error

**Comment by wangqinNick** [comment]
May I ask what kind of operation will produce “empty list” in your code, list or a message after you add a new task

**Comment by SibingWu** [comment]
> May I ask what kind of operation will produce “empty list” in your code, list or a message after you add a new task

It will display "Empty List." when there is no tasks in the duke.txt file, so nothing will be loaded to the screen

**Comment by wangqinNick** [comment]
So 2 possible reasons, is it because your duke.txt is empty or  when your program cannot find the file, it has a default constructor to build an empty task list?

**Comment by SibingWu** [comment]
> So 2 possible reasons, is it because your duke.txt is empty or  when your program cannot find the file, it has a default constructor to build an empty task list?

I think the second one is possible (since if it is the first reason, then it should display "Empty List." as expected). However I wonder how I can write the batch script to let it find the duke.txt?

**Comment by SibingWu** [comment]
Here comes another problem:

when running the project in intellij, it works perfectly fine.

However when it comes to runtest.bat, error occurs:
![image](https://user-images.githubusercontent.com/49228945/75509533-d6f52780-5a22-11ea-8cb7-bc29eb3aa55c.png)

2 problems:
1. how come there is no bug when running in intellij and there is an exception for runtest.bat
2. there is no line 90 in Duke.java
![image](https://user-images.githubusercontent.com/49228945/75509557-f5f3b980-5a22-11ea-8034-d226d48f2a35.png)

**Comment by damithc** [comment]
Search for all *.class files (that were generated by previous runs) and delete them.

**Comment by SibingWu** [comment]
> Search for all *.class files (that were generated by previous runs) and delete them.

Make sense! I wonder where I can find those .class files?

**Comment by damithc** [comment]
> Make sense! I wonder where I can find those .class files?

try `out` folder, `bin` folder (if any)

**Comment by SibingWu** [comment]
> Make sense! I wonder where I can find those .class files?
> 
> try out folder, bin folder (if any)

I deleted all .class files under the two folders, but there is another problem: java.lang.ClassNotFoundException: Duke

Such exception only occurs when runtest.bat

**Comment by damithc** [comment]
> I deleted all .class files under the two folders, but there is another problem: java.lang.ClassNotFoundException: Duke
> 
> Such exception only occurs when runtest.bat

Did you update the javac command in the runtest.bat to account for the packages you introduced?

**Comment by SibingWu** [comment]
> I deleted all .class files under the two folders, but there is another problem: java.lang.ClassNotFoundException: Duke
> Such exception only occurs when runtest.bat
> 
> Did you update the javac command in the runtest.bat to account for the packages you introduced?

I did: javac  -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\duke\*.java ..\src\main\java\duke\commands\*.java ..\src\main\java\duke\exceptions\*.java ..\src\main\java\duke\parser\*.java ..\src\main\java\duke\storage\*.java ..\src\main\java\duke\tasklist\*.java ..\src\main\java\duke\tasks\*.java ..\src\main\java\duke\ui\*.java ..\src\main\java\duke\utils\*.java

**Comment by damithc** [comment]
> I did: javac -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\duke*.java ..\src\main\java\duke\commands*.java ..\src\main\java\duke\exceptions*.java ..\src\main\java\duke\parser*.java ..\src\main\java\duke\storage*.java ..\src\main\java\duke\tasklist*.java ..\src\main\java\duke\tasks*.java ..\src\main\java\duke\ui*.java ..\src\main\java\duke\utils*.java

Does that command work when you run it manually, from the same directory as the runtest.bat?

**Comment by SibingWu** [comment]
> I did: javac -cp ..\src -Xlint:none -d ..\bin ..\src\main\java\duke*.java ..\src\main\java\duke\commands*.java ..\src\main\java\duke\exceptions*.java ..\src\main\java\duke\parser*.java ..\src\main\java\duke\storage*.java ..\src\main\java\duke\tasklist*.java ..\src\main\java\duke\tasks*.java ..\src\main\java\duke\ui*.java ..\src\main\java\duke\utils*.java
> 
> Does that command work when you run it manually, from the same directory as the runtest.bat?

It can work:
![image](https://user-images.githubusercontent.com/49228945/75511413-263e5680-5a29-11ea-8752-a6ddcec09864.png)

Actually runtest.bat successfully generates the *.class files under bin directory

**Comment by damithc** [comment]
> Actually runtest.bat successfully generates the *.class files under bin directory

Then, check the `java` command in the runtest.bat. Is it updated to use the packaged Duke class?

**Comment by SibingWu** [comment]
> Actually runtest.bat successfully generates the *.class files under bin directory
> 
> Then, check the java command in the runtest.bat. Is it updated to use the packaged Duke class?

![image](https://user-images.githubusercontent.com/49228945/75511985-f5f7b780-5a2a-11ea-8490-0a5631cb5368.png)
I wonder how I can know if it is updated?

**Comment by damithc** [comment]
> I wonder how I can know if it is updated?

See the end of [this textbook section](https://nus-cs2113-ay1920s2.github.io/website/book/cppToJava/misc/packages/).

**Comment by SibingWu** [comment]
> I wonder how I can know if it is updated?
> 
> See the end of this textbook section.

Thank you so much!!! Problem fixed!
