### ISSUE TITLE
Merge conflict issues

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#48]
![image](https://user-images.githubusercontent.com/49268567/75523541-2f3e2080-5a47-11ea-8dcb-be1857752eea.png)
When want to solve the merge conflict, I have carried out some wrong steps. Currently, my branch-A-JavaDoc is in some strange location. May I ask how to slove this and how to continue to merge master and javadoc?

If i pull the javadoc , then it becomes:
![image](https://user-images.githubusercontent.com/49268567/75523760-952aa800-5a47-11ea-88e7-0e8dd9fa0455.png)

**Comment by wangqinNick** [comment]
If what you say is you only want to merge a specific commit from other branch, use cherry pick.

**Comment by damithc** [comment]
Try this:
Reset the current branch to the previous commit (in the yellow branch) to get rid of the grey node.
Instead of `pull`, you can use `fetch` that would download the commits without trying to merge them.

**Comment by JTWang2000** [comment]
@damithc Thank you for your reply. I tried and it worked. 
![image](https://user-images.githubusercontent.com/49268567/75524956-e50a6e80-5a49-11ea-845d-b36fab090cc1.png)
But then i followed this to try to solve conflict, then my master leaves at previous stage:
![image](https://user-images.githubusercontent.com/49268567/75525019-09664b00-5a4a-11ea-8a69-59e98f9f2e78.png)

**Comment by damithc** [comment]
That's expected. The `master` branch remains as before. You are merging `master` branch to other branches, which update the receiving branch but not the `master` branch.

**Comment by JTWang2000** [comment]
@damithc Thanks. I have understood now and merged to master successfully.
