### ISSUE TITLE
Inquiry on documentation

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#49]
I wonder if there is a abstract methods for superclass and polymorphism shown in subclasses, do we need to write documentation for the abstract method in superclass? Or we just need to write documentation for that method (specific implementation) in each subclass?

**Comment by damithc** [comment]
Rather than duplicate the same comment in parent and child, it is possible for you to specify (using javadoc syntax) that a method inherits the javadoc comment from the parent. I'll leave you to find out how to do that :-)
