### ISSUE TITLE
Final-JAR

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#50]
Hello,

I have already released the JAR file using Github releases, however the iP progress dashboard shows that I have not completed the Final Jar increment. Is this because I checked the box that says it is a pre-release when publishing the release?

If that is the case, do I have to create a new release or can I simply edit the release and uncheck that option?

**Comment by Zhilin-Huang** [comment]
I think the iP progress dashboard is not updated in real time? So maybe it's because you released the JAR file after the last update

**Comment by chaosInTheWild** [comment]
Hmm I uploaded the JAR file before these new tasks were added to the dashboard though

**Comment by damithc** [comment]
@kokjoon97 you can go by the date stamp mentioned at the top of the table in the progress page.
Was the jar file added on 28th or before?
If it was later, ping me again if the jar release is not reflected by the next update to the dashboard.

**Comment by chaosInTheWild** [comment]
My final release was on the evening of 28th, not sure what time the update to the dashboard was done. I have also changed that release to be a final release for consistency because I realized I marked one of my earlier releases as a final release while this one was not.

**Comment by rdimaio** [comment]
HI, I am also having this issue; I uploaded my final .jar file in a [release called v0.2](https://github.com/rdimaio/duke/releases/tag/v0.2) on the 20th, but it shows up as gray on the iP progress dashboard.

**Comment by damithc** [comment]
> My final release was on the evening of 28th, not sure what time the update to the dashboard was done. I have also changed that release to be a final release for consistency because I realized I marked one of my earlier releases as a final release while this one was not.

@kokjoon97 dashboard updated. Your jar should be visible now.

**Comment by damithc** [comment]
> HI, I am also having this issue; I uploaded my final .jar file in a [release called v0.2](https://github.com/rdimaio/duke/releases/tag/v0.2) on the 20th, but it shows up as gray on the iP progress dashboard.

@rdimaio The script only counts jar files uploaded after Feb 22nd, in order to avoid counting late jar submission of week 6 as final jar submissions. If you uploaded the jar file before that date, the script will not count it, which is not a problem as the final iP grading does not depend on the script results alone. But if you want to keep the script happy, you can re-upload the jar again as a new release.

**Comment by chaosInTheWild** [comment]
> > My final release was on the evening of 28th, not sure what time the update to the dashboard was done. I have also changed that release to be a final release for consistency because I realized I marked one of my earlier releases as a final release while this one was not.
> 
> @kokjoon97 dashboard updated. Your jar should be visible now.

Okay thank you prof!
