### ISSUE TITLE
User Guide Not Update

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#51]
I have updated the user guide on docs/readme
However, when i am visiting the website: http://{your username}.github.io/duke/, it still appears the readme of origin duke.

**Comment by A11riseforme** [comment]
![image](https://user-images.githubusercontent.com/9150683/75610428-005da280-5b4c-11ea-8859-6a62d65fe3a2.png)
change this

**Comment by JTWang2000** [comment]
Thanks, I have fixed!
