### ISSUE TITLE
Must we update the user guide on the main page of project?

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#52]
As per issue subject. I wonder if we can just update the README.md on docs/README.md since I think the tutorial on the README.md in the original duke is quite good.

**Comment by damithc** [comment]
Not entirely sure what you mean.
`[root]/docs/README.md` is supposed to be a _user_ guide whereas `[root]/README.md` is meant for developers. So, best not to copy content from latter to the former.
Is that what you wanted to know?

**Comment by SibingWu** [comment]
> Not entirely sure what you mean.
> [root]/docs/README.md is supposed to be a user guide whereas [root]/README.md is meant for developers. So, best not to copy content from latter to the former.
> Is that what you wanted to know?

Yes! Thank you prof!
