### ISSUE TITLE
Github Page for User Guide not showing

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#53]
Hello, the Github page for my user guide says it has been published, but when I access the link, there is no page available. Anyone able to help with this?
![problem1](https://user-images.githubusercontent.com/54733974/75622534-482c0a80-5bdc-11ea-85db-0044bf5c9721.PNG)
![problem2](https://user-images.githubusercontent.com/54733974/75622533-46fadd80-5bdc-11ea-9260-723048ea380b.PNG)

**Comment by damithc** [comment]
Try pushing another commit to see if that makes a difference.

**Comment by brandoncjh** [comment]
Yup, it works now. Thanks Prof!
