### ISSUE TITLE
How to convert a java project into gradle project

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#54]
1. How to convert an existing ordinary java project into a gradle project in intellij. In Topic, it seems that it only mentions how to create brand new gradle and import existing gradle project.
2. Do we need to convert it to gradle project for iP?

**Comment by damithc** [comment]
> 2\. Do we need to convert it to gradle project for iP?

No. We start using Gradle in the tP.

**Comment by SibingWu** [comment]
> > 2. Do we need to convert it to gradle project for iP?
> 
> No. We start using Gradle in the tP.

Ok Thank you
