### ISSUE TITLE
iP Admin Tasks: Merged branch not found

### ISSUE THREAD

**Issue by Keith-JK** [nus-cs2113-AY1920S2/forum#55]
Hi, 
![image](https://user-images.githubusercontent.com/42379488/75623760-4f591580-5be8-11ea-8c54-655aaa512496.png)

According to the iP Progress Dashboard, the merged branch-Level-X has not been found in the fork although I have merged the latest master to all the existing branches as a merge commit that is reflected in the branches itself. 

Have i misunderstood the instructions? If so, please advise. Thank you

**Comment by damithc** [comment]
_merged_ generally means _merged to `master`.

When you merge `master` to another branch, it is simply a case of updating the branch to the latest changes in the `master` branch. The code in those branches don't appear in the product until you merge the branch to `master`.

Hence, we are looking for branches merged to master as only that indicates the work done on those branches have reached the expected end goal.

**Comment by Keith-JK** [comment]
It seems that i had misunderstood the instructions here.
![image](https://user-images.githubusercontent.com/42379488/75624511-c6de7300-5bef-11ea-8945-8e3623635a87.png)
I had completed the merged branches-level-X (did the work in the branch and merge it to master) prior to this mistake and it seems that the script cannot detect them anymore when it could the last time. What are the steps i should take to allow the script to properly pick up the merged branches again?

**Comment by damithc** [comment]
What do those branches contain anyway? As you have not merged them to the master branch, you current app is not using any code from those branches.
Can you post a screenshot showing the full length of those branches?

**Comment by Keith-JK** [comment]
Prior to the merging the master to each of the branches, branches contain work done for the respective increments i.e. Branch-Level-6 contains the increment Level-6 which is subsequently merged to master in a merge commit as per Level-6 increments instructions in that particular week and left alone thereafter. This applies for Level-5, Level-6 and Level-7 increments as can be seen below:
![image](https://user-images.githubusercontent.com/42379488/75626267-18dbc480-5c01-11ea-9c96-90a62d886ed2.png)
Level-9 increments and A-JavaDoc were merged to master through a PR requests as seen below:
![image](https://user-images.githubusercontent.com/42379488/75626289-4d4f8080-5c01-11ea-984a-5a10c08d3834.png)
![image](https://user-images.githubusercontent.com/42379488/75626322-97d0fd00-5c01-11ea-97ed-e48ea5ddcdaf.png)
However, due to the recent incorrect merges as can be seen above where i incorrectly merge master into all branches, all of them now contain the same code as master which is the most recent increment A-Release.

**Comment by damithc** [comment]
> However, due to the recent incorrect merges as can be seen above where i incorrectly merge master into all branches, all of them now contain the same code as master which is the most recent increment A-Release.

In that case, just merge them back to master and push the branches to the fork. The master code will remain unchanged but the branches will then be considered as 'merged'.

**Comment by Keith-JK** [comment]
Ok thank you
