### ISSUE TITLE
Clarification on iP evaluation 

### ISSUE THREAD

**Issue by JLoh579** [nus-cs2113-AY1920S2/forum#59]
When I was running an iP's Jar file for evaluation using the  `java -jar {file_name}` command, I got a "java.lang.UnsupportedClassVersionError" which says that it has been compiled by a more recent version of the Java Runtime (class file version 56.0). (Picture below)

![Jar error](https://user-images.githubusercontent.com/42561929/76143536-24246980-60b3-11ea-9dc8-89b6a5dde8ac.PNG)

According to this website: [https://mkyong.com/java/java-lang-unsupportedclassversionerror/](url) , class file version 56 refers to JDK 12. So I'm guessing I can't run it because I'm using JDK 11. 
May I clarify how I should go about the peer evaluation? More specifically, is it ok for me to download the source files and compile it myself for testing and evaluation? Or do I evaluate the program as is (not able to run)?

**Comment by damithc** [comment]
> May I clarify how I should go about the peer evaluation? More specifically, is it ok for me to download the source files and compile it myself for testing and evaluation? Or do I evaluate the program as is (not able to run)?

@JLoh579 Nice of you to offer to compile it yourself, but it's the responsibility of the author to provide a jar file compatible with the specified version.
If you wish (no obligation), you can post in the issue tracker of the author to request for a compatible jar to be uploaded. 
Alternatively (or if the author does not provide a rectified jar file quickly enough), you can evaluate it as is (i.e., not able to run).

**Comment by JLoh579** [comment]
Ok, issue posted, thanks Prof!
