### ISSUE TITLE
Will the answers to tutorial exercises be posted?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#60]
I noticed that there are some exercises in [Week 8 Tutorial](https://nus-cs2113-ay1920s2.github.io/website/schedule/week8/tutorial.html) - just wondering whether the answers to these exercises will be posted?

**Comment by damithc** [comment]
Normally, we don't. But we'll share the answers this time because some of you may not be able to attend tutorials this time.

**Comment by Zhilin-Huang** [comment]
Thanks Prof!
