### ISSUE TITLE
Clarification on possible typo in UML notes

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#61]
https://nus-cs2113-ay1920s2.github.io/website/book/uml/classDiagrams/associations/navigability/

In the exercise, it says, "In the implementation, the `Unit` object will hold a `Unit` object in one of its variables." Was wondering if the 2nd Unit was meant to be an Item instead?

**Comment by damithc** [comment]
You are right @brandoncjh 
Thanks for the bug report. Fixed.
