### ISSUE TITLE
Facing a weird issue regarding the printing of lines and scanning of input

### ISSUE THREAD

**Issue by dejunnn** [nus-cs2113-AY1920S2/forum#65]
Hi everyone. I am facing a really weird issue and I honestly have no idea why it is happening.

![image](https://user-images.githubusercontent.com/51941453/76331093-a1f1aa80-6329-11ea-9382-5f2ffc291e72.png)

In the attached picture is a snippet of my code with a few checks to see how it prints. I would expect "Check 1" to be printed before I enter the user input but it only gets printed after scanning in userAge which is very weird. The same happens for userGender, where "Check 3" gets printed after the input.

![image](https://user-images.githubusercontent.com/51941453/76330897-5a6b1e80-6329-11ea-96a9-92b14005c10a.png)

When I change all the println() statements to print() statements it ends up becoming weirder as they do not get printed until all the inputs have been entered. May I know why this is the case and why this happens? Because it does not make much sense to me personally.

![image](https://user-images.githubusercontent.com/51941453/76330986-779fed00-6329-11ea-9c41-5aa66fa75c72.png)

This issue seems simple enough but I have no idea why it's happening this way. Hopefully, someone would be able to help me out :)

**Comment by A11riseforme** [comment]
"check1" and "check2" will remain in the buffer until a newline "\n" is at the end, which is "Please enter your gender\n", then these three strings will be printed to the stdout together.

**Comment by dejunnn** [comment]
Why does this happen though? I tried using an online java compiler and runner and it works fine, where I can put my input on the same line as the printed prompt

![image](https://user-images.githubusercontent.com/51941453/76332372-42949a00-632b-11ea-9c46-0bfaa576e97e.png)

Why is there a difference with the 2 results?

**Comment by damithc** [comment]
@dejunnn What happens when you use the OS terminal to run the app (not Intellij)?

On a separate note, the app is supposed to take all data items in one command, not one data item at a time.

**Comment by dejunnn** [comment]
![image](https://user-images.githubusercontent.com/51941453/76391805-36502180-63ab-11ea-8502-f2b8afe67b82.png)


It works fine when i replace the println() to print(). The error only occurs when I run it using Intellij/Gradle. Not sure why that is happening.

Oh, noted prof :) I was just doing this initially to test the input all at once when I encountered this issue.

**Comment by damithc** [comment]
> It works fine when i replace the println() to print(). The error only occurs when I run it using Intellij/Gradle. Not sure why that is happening.

I assume you know the difference between pritntln() and print().
Intellij could be using some internal buffering that makes the output look weird. It's fine as long as the code works correctly in the normal console as that is where the product will eventually run.

**Comment by dejunnn** [comment]
Oh ok noted.  Makes testing a little harder but I guess I can work around it. Thanks a bunch :)
