### ISSUE TITLE
Do we need to publish User Guide for tP v1.0?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#66]
We've submitted UG v1.0 before during tutorial, but do we need to publish the UG v1.0 on GitHub like we did for iP?

**Comment by damithc** [comment]
Which tP requirement in which week are you referring to?
Anyhow, yes the tP UG must be published on GitHub. Your project template comes with a UG file that you need to update https://github.com/nus-cs2113-AY1920S2/tp/blob/master/docs/UserGuide.md

**Comment by Zhilin-Huang** [comment]
> Which tP requirement in which week are you referring to?
> Anyhow, yes the tP UG must be published on GitHub. Your project template comes with a UG file that you need to update https://github.com/nus-cs2113-AY1920S2/tp/blob/master/docs/UserGuide.md

Okay, we'll update and publish UG v1.0 on GitHub!
I was asking about tP v1.0 requirements for Week 8 and 9 because I cannot seem to find a requirement corresponding to UG update.

**Comment by damithc** [comment]
> I was asking about tP v1.0 requirements for Week 8 and 9 because I cannot seem to find a requirement corresponding to UG update.

Updating UG is not required at v1.0, but you are welcome to update the UG as you go.

**Comment by Zhilin-Huang** [comment]
> > I was asking about tP v1.0 requirements for Week 8 and 9 because I cannot seem to find a requirement corresponding to UG update.
> 
> Updating UG is not required at v1.0, but you are welcome to update the UG as you go.

Noted! Thanks Prof
