### ISSUE TITLE
Unable to run JUnit tests

### ISSUE THREAD

**Issue by brandoncjh** [nus-cs2113-AY1920S2/forum#67]
I am having issues with trying to build and run the JUnit tests. For example, using the default tests provided, the test classes encounter an error when trying to build the module, IntelliJ is unable to import the Assertions class:
![capture1](https://user-images.githubusercontent.com/54733974/76393399-7238b600-63ae-11ea-87ba-3140e02e7e12.PNG)
After adding the recommended library to the classpath:
![Screenshot (36)](https://user-images.githubusercontent.com/54733974/76393406-74027980-63ae-11ea-9d6c-25534f18ec30.png)
I can build the module, but trying to run all tests it gives this error:
![capture2](https://user-images.githubusercontent.com/54733974/76393402-7369e300-63ae-11ea-965f-e52eb4f69f75.PNG)
Is there any way to rectify this? Have tried deleting and reimporting the project but it makes no difference.

**Comment by damithc** [comment]
After importing the project, are you able to run the `gradlew test` successfully? That task runs the default JUnit test as well.

**Comment by brandoncjh** [comment]
Yes, it says build successful.
![capture1](https://user-images.githubusercontent.com/54733974/76396765-c5ae0280-63b4-11ea-97eb-34286dbca453.PNG)

**Comment by damithc** [comment]
That means you can use that method to run your JUnit tests if other methods don't work.

In the meantime, try clicking the 'refresh' icon in the Gradle windows to see if that helps with the other problem.
![image](https://user-images.githubusercontent.com/1673303/76400954-1bd27400-63bc-11ea-97f8-45f63f251d63.png)

**Comment by brandoncjh** [comment]
After uninstalling and reinstalling IntelliJ, it seems I can run the tests now. Very weird:
![capture2](https://user-images.githubusercontent.com/54733974/76484204-10328c00-6454-11ea-8fef-7a516537c5d2.PNG)

Thank you for the help Prof!
