### ISSUE TITLE
Week 9 Quiz Part 2 is worth 0 mark?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#68]
It seems that Week 9 Quiz Part 2 is worth 0 mark - is this a mistake?
![image](https://user-images.githubusercontent.com/31772358/76427746-ac727980-63e7-11ea-911d-e6df212b5328.png)

**Comment by damithc** [comment]
It's a LumiNUS bug. Will contact NUS IT to see if they can help. Meanwhile, you can go ahead and attempt the quiz as marks calculation can be changed later.

**Comment by Zhilin-Huang** [comment]
> It's a LumiNUS bug. Will contact NUS IT to see if they can help. Meanwhile, you can go ahead and attempt the quiz as marks calculation can be changed later.

Noted with thanks

**Comment by damithc** [comment]
Fixed
