### ISSUE TITLE
Week 8 Tutorial Exercise 3

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#69]
Does anyone know why `Alfred` and `Bruce` are using the same home address? I know it's logical to assume they have the same home address since `Alfred` is a guardian of `Bruce`, but this is not explicitly mentioned.

The screenshot is as below:
![image](https://user-images.githubusercontent.com/31772358/76441962-2bbd7880-63fb-11ea-9516-9f6debcc250a.png)

**Comment by g-lilian** [comment]
It was mentioned during tutorial that it's because the question stated to assume that we are trying to minimize the number of total objects.

**Comment by Zhilin-Huang** [comment]
> It was mentioned during tutorial that it's because the question stated to assume that we are trying to minimize the number of total objects.

Oh I see! Thanks
