### ISSUE TITLE
Sentence Phrasing Clarification

### ISSUE THREAD

**Issue by kcubey** [nus-cs2113-AY1920S2/forum#7]
Under Week 2 > Project > iP > Point 4, it says 
'In this initial skeletal version of Duke, it starts by greeting the user, simply echos commands entered by the user, and exits when the user types bye. '

Wording should be corrected/added to, and state something along the lines of 'You are to modify the current duke project to implement the following:' to reduce confusion as to what the task actually is. The phrasing seems to imply that duke already does the above stated functions

**Comment by damithc** [comment]
Good point @kcubey 
I've updated the phrasing.
