### ISSUE TITLE
Build keeps failing with assertion error

### ISSUE THREAD

**Issue by g-lilian** [nus-cs2113-AY1920S2/forum#70]
After I opened a PR for some JUnit tests, the build keeps failing on Github with an assertion error in one of the tests. However, when I run the test locally, the build is successful. I'm not sure how to debug the test in Intellij because the local build doesn't have any errors.
We initially suspected that this was due to the list (checked in the assertion) being modified in some other tests, but even after I reinitialized the list to be private to the failed test, the problem still persists.

Any suggestions as to how to resolve this issue?

**Comment by damithc** [comment]
It might help if you share the link to the failing PR/commit/branch

**Comment by g-lilian** [comment]
Noted, here is the link to the PR: https://github.com/AY1920S2-CS2113-T14-1/tp/pull/43

**Comment by damithc** [comment]
Which OS are you using? If it is Windows, you might want to get a team member using Linux or OS-X to run the tests for you as the GitHub failure is indicated on ~~Windows~~ Ubuntu.

**Comment by g-lilian** [comment]
Thanks prof.  The issue has been resolved. The assertion error was caused by some other constants being modified. Strangely enough, the error did not show up in my Intellij but it did on my teammate's Intellij.
