### ISSUE TITLE
Issues with runtest.bat for tp

### ISSUE THREAD

**Issue by JLoh579** [nus-cs2113-AY1920S2/forum#71]
Hi,
Our team is having issues with the tp, when we try to run the runtest.bat in the terminal. The program works fine when we run it using Gradle in IntelliJ, however, we keep getting this error when we run the runtest.bat:
BUILD SUCCESSFUL in 11s
2 actionable tasks: 2 executed
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at seedu.duke.Duke.readCommand(Duke.java:68)
        at seedu.duke.Duke.runCommandLoopUntilExitCommand(Duke.java:53)
        at seedu.duke.Duke.run(Duke.java:30)
        at seedu.duke.Duke.main(Duke.java:24)
Test failed!

Currently we have the following code to read commands from user input:
private static Scanner in = new Scanner(System.in);

// some other code

public String readCommand() {
        String input = "";
        while (input.isEmpty()) {
            input = in.nextLine();
            input.trim();
        }
        return input;
    }

Please advise. Thanks in advance!

**Comment by damithc** [comment]
Just a note: Gradle doesn't run the runtest.bat (but GitHub runs it when you push code to your repo). If there is a problem with the runtest.bat, running gradle locally will not help you find it.

**Comment by damithc** [comment]
It might help if you can share a link to the commit/branch that has the problematic code.

**Comment by chaosInTheWild** [comment]
Hi, on behalf of the OP, this is the commit where our team last edited the code that had to do with scanning of user input: 
[Link to commit](https://github.com/AY1920S2-CS2113T-T13-1/tp/commit/225e70a3d37bb2d16036bf502fad3d28b95ded1c)

**Comment by damithc** [comment]
You guys have so many 'broken' commits it's hard to know when something broke (shouldn't have merged any PR that doesn't pass CI). Any idea which was the latest commit that did _not_ have this problem? 

There are many PRs [here](https://github.com/nus-cs2113-AY1920S2/tp/pulls) that pass CI (i.e., the ones with the green tick), which means their runtest.bat is working. You can compare their code to yours to see if there is any difference in the way you use the Scanner.

**Comment by chaosInTheWild** [comment]
It seems I have resolved the issue by changing the path to 'dir /b duke-0.0.1.jar' in the runtest.bat file where it was previously 'dir /b *.jar'. I don't think it was an issue with the Scanner like IntelliJ was warning about, it seemed no matter how I changed the code, it kept warning about the same line of code even though that line only contained a curly bracket.

I have just merged a PR which passes all the CI tests.

EDIT: Not very sure why shadowJar creates two different jar files in the build/libs directory, of which only one works (duke-0.0.1.jar)

**Comment by damithc** [comment]
> Not very sure why shadowJar creates two different jar files in the build/libs directory, of which only one works (duke-0.0.1.jar)

It seems you had a stale jar file in your lib directory which was being used for the test, instead of the latest jar file. Shadowjar creates only one jar file.
`gradlew clean` should get rid of those stale files.

**Comment by chaosInTheWild** [comment]
Ohhhh I see, that explains why one of the jar files had such weird behaviour. Thanks for clarifying prof!
