### ISSUE TITLE
New update cannot be found in tp code dashboard.

### ISSUE THREAD

**Issue by RenzoTsai** [nus-cs2113-AY1920S2/forum#73]
Our tp PR was closed by mistake and I have reopened it. But after reopening, it seems that the new update of our code cannot be tracked in tp code dashboard. Here is the link of our [tp PR](https://github.com/nus-cs2113-AY1920S2/tp/pull/27)
How can I fix this problem? Thanks in advance!

**Comment by damithc** [comment]
tP code dashboard is not linked to the team PR. It is only based on the code in the `master` branch of your team repo, and is updated only once per 24 hours. Does that clarify the situation or is something still amiss?

**Comment by Zhilin-Huang** [comment]
To add on to this problem - I think our team have followed the forking workflow but this task it is not marked as done for us (or anyone else in the class?)

**Comment by damithc** [comment]
> To add on to this problem - I think our team have followed the forking workflow but this task it is not marked as done for us (or anyone else in the class?)

It's not being checked yet. 

![image](https://user-images.githubusercontent.com/1673303/76540456-20328600-64bd-11ea-82d7-8aa42c3143d4.png)

**Comment by Zhilin-Huang** [comment]
> It's not being checked yet.

I see :) Thanks Prof!

**Comment by RenzoTsai** [comment]
> tP code dashboard is not linked to the team PR. It is only based on the code in the `master` branch of your team repo, and is updated only once per 24 hours. Does that clarify the situation or is something still amiss?

Yeah, and our code is updated now. Thank you, professor!
