### ISSUE TITLE
Arrow pointing the wrong way in the new UML video?

### ISSUE THREAD

**Issue by rdimaio** [nus-cs2113-AY1920S2/forum#75]
I think the error may be in the diagram drawn for Q2(b) in the bottom left corner. 
It says "one ActionX object containing one Task object has been created and added to the History"; I think it means that :ActionX should be added to :History (in which case History should point to :ActionX instead of :Task)
(supported by the fact that History adds Repeatable objects, which is an interface implemented by Action, but not by Task)

**Comment by damithc** [comment]
Anyone agrees (or disagrees)?

**Comment by damithc** [comment]
@rdimaio Closing this issue in favor of #76, but if your idea turns out to be correct, you will be considered for the price (based on the time of this post).

**Comment by damithc** [comment]
Your answer is correct @rdimaio 
I'll send you the voucher for the T-shirt.
