### ISSUE TITLE
1. How to tell the difference between composition and aggregation

### ISSUE THREAD

**Issue by lowxizhi** [nus-cs2113-AY1920S2/forum#77]
In this case, there is a composition association between Email class and Subject object

class Email {
    private Subject subject;
  ...
}

In this case, there is an aggregation association between Team class and Person object.

class Team {
    Person leader;
    ...
    void setLeader(Person p) {
        leader = p;
    }
}

**Comment by damithc** [comment]
You can edit your own issues. No need to close and open a new one :-)

**Comment by lowxizhi** [comment]
I accidentally posted this issue by pressing Enter. Will take note!
