### ISSUE TITLE
Failed I/O redirection test

### ISSUE THREAD

**Issue by itskesin** [nus-cs2113-AY1920S2/forum#79]
![image](https://user-images.githubusercontent.com/42372373/76696865-1da57b80-66cb-11ea-8ad4-4f343d77a391.png)

Hi,
I failed my I/O redirection test in git when I tried to create a pull request. I have no idea how to resolve this problem? Can somebody give me some guidance?

**Comment by damithc** [comment]
The first step is to find out at which commit this test started failing. Whatever change you did in that commit is the thing causing the problem.  To check if the test is failing at a particular commit, checkout the commit in git and then run the runtest.bat (after checking out a commit, you might want to run `gradlew clean` to ensure all class files generated by the previous commit is deleted). 

(`git bisect` is a better way to locate which commit introduced a bug but that's an advanced technique; if you want to use that, you'll have to learn it yourself).
