### ISSUE TITLE
Inquiry on Ex4: getMultipleGradeCaps

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#8]
When running the test case, it shows "assertEquals(Arrays.toString(new double[]{5.0, 0, 2.5, 3.0}), Arrays.toString(Main.getMultipleGradeCaps(new String[]{"A+", "Foo", "C", "B-"})));"

It seems that it expects "0" instead of "0.0" for "Foo". However, as a double, the result will be 0.0. In this case, should we do any special manipulation on "0.0" case?

**Comment by damithc** [comment]
> It seems that it expects "0" instead of "0.0" for "Foo".

Are you sure this is the cause of the test failure? As no one else reported a similar problem,  my initial thought is that the test failure caused by something something else.  🤔

**Comment by SibingWu** [comment]
> > It seems that it expects "0" instead of "0.0" for "Foo".
> 
> Are you sure this is the cause of the test failure? As no one else reported a similar problem, my initial thought is that the test failure caused by something something else.

I found the reason, due to the wrong function name...
