### ISSUE TITLE
Jar has no manifest attribute

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#80]
I generated the jar file for tp via
project structure -> artifacts -> JAR -> from modules with dependencies -> <All modules>
however, when running the jar file, terminal shows that "jar has no manifest attribute"
I wonder how I can fix it?
![image](https://user-images.githubusercontent.com/49228945/76753608-da770580-67bb-11ea-9269-52d795d06b20.png)

**Comment by A11riseforme** [comment]
`gradlew shadowJar`

**Comment by SibingWu** [comment]
> gradlew shadowJar

then where can find the generated jar file?

**Comment by damithc** [comment]
> then where can find the generated jar file?

More info in the gradle tutorial that came with your tP https://github.com/nus-cs2113-AY1920S2/tp/blob/master/tutorials/gradleTutorial.md

**Comment by A11riseforme** [comment]
build/libs

**Comment by SibingWu** [comment]
> build/libs

Thank you, problem fixed!
