### ISSUE TITLE
Week 10 Post-lecture quiz

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#82]
Hi,
It seems that in LumiNUS, I am only able to see Week 10 - Quiz Part II. Can I check if there is supposed to be a part I which I am not seeing in the quizzes section?

**Comment by damithc** [comment]
Try now. I've updated the settings.

**Comment by chaosInTheWild** [comment]
Okay I see it now! Thank you prof!
