### ISSUE TITLE
Path coverage and statement coverage

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#83]
Understood from the explanation that 100% path coverage gives the highest intensity, but why doesn't 100% statement coverage give highest intensity as well? Doesn't all statements being executed mean all paths are executed?

![image](https://user-images.githubusercontent.com/31772358/77057085-62544e00-6a0e-11ea-860a-69586b9d91db.png)

Any help is appreciated!

**Comment by damithc** [comment]
Good question @Zhilin-Huang 
Consider a case of a while-loop in the code. An execution path that does only one iteration through the loop executes all statements in the loop, achieving 100% statement coverage. But that does not mean _all unique paths through the loop_ have been executed because a path that does only one iteration in the loop is different from another path that does two iterations in the loop.

**Comment by Zhilin-Huang** [comment]
> Good question @Zhilin-Huang
> Consider a case of a while-loop in the code. An execution path that does only one iteration through the loop executes all statements in the loop, achieving 100% statement coverage. But that does not mean _all unique paths through the loop_ have been executed because a path that does only one iteration in the loop is different from another path that does two iterations in the loop.

I see! So does this mean that in the case that we have a while-loop, we can never achieve 100% path coverage because executing 1, 2, 3... n iterations are considered different paths?

**Comment by damithc** [comment]
> I see! So does this mean that in the case that we have a while-loop, we can never achieve 100% path coverage because executing 1, 2, 3... n iterations are considered different paths?

Yes, if the possible number of loops is not a fixed number of possibilities. In other cases it is not _impossible_ but the number of paths can be too big for 100% path coverage to be _feasible_.

**Comment by Zhilin-Huang** [comment]
> > I see! So does this mean that in the case that we have a while-loop, we can never achieve 100% path coverage because executing 1, 2, 3... n iterations are considered different paths?
> 
> Yes, if the possible number of loops is not a fixed number of possibilities. In other cases it is not _impossible_ but the number of paths can be too big for 100% path coverage to be _feasible_.

Thanks for the clarification Prof!
