### ISSUE TITLE
RepoSense not recording some of my code contributions

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#84]
Hi,
In order for the code to be RepoSense-compatible, does this mean that all the code contributions by me should be recorded in the code dashboard? 

Currently, it seems that the code that is attributed to me in the dashboard is indeed contributed by me however some of the other code portions which I have written as well are not reflected in the dashboard but are instead showing up in the dashboard for other members of my team. Do I have to create the config.json file to fix this? Its just one method that is missing though so I'm not sure if its considered a serious issue too

**Comment by damithc** [comment]
> In order for the code to be RepoSense-compatible, does this mean that all the code contributions by me should be recorded in the code dashboard?

Yes. At least the code you want to take credit for should be attributed to you by RepoSense, as some of our grading components (e.g., code quality) is based on the code attributed to you by the RepoSense report.

> Currently, it seems that the code that is attributed to me in the dashboard is indeed contributed by me however some of the other code portions which I have written as well are not reflected in the dashboard but are instead showing up in the dashboard for other members of my team. Do I have to create the config.json file to fix this?

RepoSense attributes a line to whoever touched it last. If you want to claim credit for code that could have been touched by others later, you can use `@@author` tags, as described [here](https://github.com/reposense/RepoSense/blob/release/docs/UserGuide.md#provide-data-using-author-tags).

> Its just one method that is missing though so I'm not sure if its considered a serious issue too

If you are OK not claiming credit for that method, you can just leave it be.

**Comment by chaosInTheWild** [comment]
Ah okay so I only have to add the @@author tag in the code? I thought it was a much more complex process. Thanks for clarifying prof!
