### ISSUE TITLE
Tutorial 9 Exercise Answers

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#85]
Is it possible for the teaching team to share Tutorial 9 Exercise Answers with us? :)

**Comment by damithc** [comment]
Thanks for the reminder @Zhilin-Huang . Posted as an announcement.

**Comment by Zhilin-Huang** [comment]
> Thanks for the reminder @Zhilin-Huang . Posted as an announcement.

Hmmm I cannot seem to find the announcement @damithc ? The latest announcement is the one about Week 10 Tutorial arrangement.

**Comment by damithc** [comment]
> Hmmm I cannot seem to find the announcement @damithc ? The latest announcement is the one about Week 10 Tutorial arrangement.

Sorry, it turns out I posted it in the wrong module :-p
Re-posted it in CS2113 just now.

**Comment by Zhilin-Huang** [comment]
> > Hmmm I cannot seem to find the announcement @damithc ? The latest announcement is the one about Week 10 Tutorial arrangement.
> 
> Sorry, it turns out I posted it in the wrong module :-p
> Re-posted it in CS2113 just now.

Just saw the announcement :) Thanks!
