### ISSUE TITLE
Final exam format?

### ISSUE THREAD

**Issue by Zhilin-Huang** [nus-cs2113-AY1920S2/forum#87]
Will we have in-person final exam for the course? I think many exchange students have already left NUS.

**Comment by damithc** [comment]
Yes, we will have a final on-site exam. There will be an alternative assessment option given to exchange students who are no longer in Singapore.

**Comment by Zhilin-Huang** [comment]
> Yes, we will have a final on-site exam. There will be an alternative assessment option given to exchange students who are no longer in Singapore.

Noted with thanks!
