### ISSUE TITLE
Markdown syntax

### ISSUE THREAD

**Issue by JTWang2000** [nus-cs2113-AY1920S2/forum#88]
When I am implementing the UG, I want to write things in different lines so I use `</p>`. This works when I display in Github:

**This is the code for UG:**
![image](https://user-images.githubusercontent.com/49268567/77439794-78a14600-6e22-11ea-8165-756b4bad5a7d.png)

**This is the display when I see it on github or my IDE:**
![image](https://user-images.githubusercontent.com/49268567/77439668-4c85c500-6e22-11ea-9d58-26356345f835.png)

**However, when I see it on the website of my project, the </P> will displayed:**
![image](https://user-images.githubusercontent.com/49268567/77439990-b4d4a680-6e22-11ea-9f91-54087aca3a16.png)

I am confused why this happens.
I also wonder how to add return in markdown.

**Comment by damithc** [comment]
The parser used for GitHub preview is likely to be different from the one used to generate the GitHub pages. To ensure there is a line break in the generated html page, try using two consecutive blank lines instead of one.

**Comment by rdimaio** [comment]
GitHub uses a version of Markdown called [GitHub Flavored Markdown (GFM)](https://github.github.com/gfm/), which implements things in a slightly different way than standard Markdown. [This section in particular](https://github.github.com/gfm/#why-is-a-spec-needed-) talks about the `<p>` HTML tag.

**Comment by JTWang2000** [comment]
@damithc @rdimaio Thank you for the reply. I will try to add line break by using two consecutive blank lines instead of one.
