### ISSUE TITLE
Committing Increments 

### ISSUE THREAD

**Issue by matthewc97** [nus-cs2113-AY1920S2/forum#9]
I have followed the instructions given under the Week 2 Project tab to set up the project. After making changes for increment Level-1, committing and pushing it, I realised that my fork of Duke is public and I am unable to make it private without duplicating it. Can I check if we are supposed to leave it as public or otherwise? Thank you.
![github](https://user-images.githubusercontent.com/47091828/72662353-0f1b4a80-3a21-11ea-9f29-f6540ce69195.JPG)

**Comment by matthewc97** [comment]
Perhaps I have misread the instructions given for adding increments. Are we supposed to just commit locally without pushing it?

**Comment by Zhilin-Huang** [comment]
I believe the prof has mentioned during the first lecture that our repos are to remain public. Correct me if I'm wrong :)

**Comment by matthewc97** [comment]
> I believe the prof has mentioned during the first lecture that our repos are to remain public. Correct me if I'm wrong :)

In that case, are we still supposed to push our commits to the public repo?

**Comment by damithc** [comment]
> I believe the prof has mentioned during the first lecture that our repos are to remain public. Correct me if I'm wrong :)

That's correct. Thanks @Zhilin-Huang 

> In that case, are we still supposed to push our commits to the public repo?

Yes, but no need to push this week. You'll need to push your code from week 3.

**Comment by Zhilin-Huang** [comment]
> > I believe the prof has mentioned during the first lecture that our repos are to remain public. Correct me if I'm wrong :)
> 
> That's correct. Thanks @Zhilin-Huang
> 
> > In that case, are we still supposed to push our commits to the public repo?
> 
> Yes, but no need to push this week. You'll need to push your code from week 3.

Thanks for the clarification!

**Comment by matthewc97** [comment]
> > I believe the prof has mentioned during the first lecture that our repos are to remain public. Correct me if I'm wrong :)
> 
> That's correct. Thanks @Zhilin-Huang
> 
> > In that case, are we still supposed to push our commits to the public repo?
> 
> Yes, but no need to push this week. You'll need to push your code from week 3.

Thank you for the clarification!
