### ISSUE TITLE
CATcher unauthorized user

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#90]
When I logged into CATcher using github for the first time, it saids that
![image](https://user-images.githubusercontent.com/49228945/77533754-6848a400-6ed2-11ea-9168-6e8dca37b4f7.png)
How I can fix it?

**Comment by damithc** [comment]
You are trying to access a session of `CS2103`. Our module code is `CS2113`.

**Comment by SibingWu** [comment]
> You are trying to access a session of CS2103. Our module code is CS2113.

my bad... thx prof!
