### ISSUE TITLE
Video link for W12.1b seems to be invalid and a typo in W12.2b

### ISSUE THREAD

**Issue by GanapathySanathBalaji** [nus-cs2113-AY1920S2/forum#94]
1) The video link mentioned on the website for W12.1b leads to an invalid session on Panopto.

![image](https://user-images.githubusercontent.com/59698024/78419996-cd905800-767d-11ea-94dd-c6b1ce65f0e8.png)

2) Should the line (under W12.2b) be changed to the following?

Testing all pairs between p1 and p3 only while ensuring all **~~p3~~ p2** values are tested at least once

![image](https://user-images.githubusercontent.com/59698024/78420047-3ed00b00-767e-11ea-811d-7ae6950b2f74.png)

**Comment by damithc** [comment]
Thanks for the bug report @GanapathySanathBalaji 
It should be https://mediaweb.ap.panopto.com/Panopto/Pages/Viewer.aspx?id=0edaf584-6ba5-4b05-8f98-ab8e00bfc897

A fix is in progress.

**Comment by damithc** [comment]
Fixed.
