### ISSUE TITLE
Saving markdown file to pdf

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#95]
Hello,
Can I check if there is a recommended way of converting our md files into pdf format (since it seems the final submission for the portfolio page is in pdf)?

It seems I am unable to save the md file as any other file format and I'm not sure if it is safe to rely on an online converter also. When I tried to print as pdf on the rendered md file on Github, it then has the problem of including the UI of the webpage as well.

**Comment by damithc** [comment]
Instead of converting md -> pdf, you should convert the generated html file (in your github.io site) to pdf. Steps are similar to [this](https://nus-cs2113-ay1920s2.github.io/website/admin/usingThisWebsite.html#saving-as-pdf-files).

**Comment by chaosInTheWild** [comment]
Okay thank you for clarifying prof!
