### ISSUE TITLE
"Submit post-lecture quiz" missing from Week 12 Admin info section

### ISSUE THREAD

**Issue by rdimaio** [nus-cs2113-AY1920S2/forum#96]
![image](https://user-images.githubusercontent.com/35903974/78468393-3218e900-774a-11ea-8b7f-38626b13831c.png)

Whereas for week 11:

![image](https://user-images.githubusercontent.com/35903974/78468397-38a76080-774a-11ea-9577-ec0af4a5626b.png)

**Comment by damithc** [comment]
Good catch @rdimaio 
Fixed.
