### ISSUE TITLE
Incorrect format of content inside `Topic` tab

### ISSUE THREAD

**Issue by SibingWu** [nus-cs2113-AY1920S2/forum#97]
The format seems problematic here.

![image](https://user-images.githubusercontent.com/49228945/78469010-7a86d580-774f-11ea-929f-d75650096944.png)

**Comment by damithc** [comment]
Can you elaborate?

**Comment by SibingWu** [comment]
> Can you elaborate?

![image](https://user-images.githubusercontent.com/49228945/78469071-0ef13800-7750-11ea-9290-fb9e87e2f668.png)
The overall format looks like this. I cannot see the content for "What BVA recommends"; it is blocked

**Comment by damithc** [comment]
Looks fine to me. May be a caching issue. Try force-reloading the page?
![image](https://user-images.githubusercontent.com/1673303/78469201-90959580-7751-11ea-998b-9692fd61fd06.png)

**Comment by SibingWu** [comment]
> Looks fine to me. May be a caching issue. Try force-reloading the page?

I restart the whole browser but the problem still exists; however, when I changed another browser, it is normal now

**Comment by A11riseforme** [comment]
ctrl+F5

**Comment by SibingWu** [comment]
> ctrl+F5

still problematic

**Comment by damithc** [comment]
Which Browser is problematic?

**Comment by SibingWu** [comment]
> Which Browser is problematic?

EDGE

**Comment by damithc** [comment]
Yes, older Edge Browsers seem to have this problem. Upgrade to the new edge:
![image](https://user-images.githubusercontent.com/1673303/78469431-db181180-7753-11ea-876f-f4f0a0314cbf.png)

**Comment by SibingWu** [comment]
> Yes, older Edge Browsers seem to have this problem. Upgrade to the new edge:

OK, thx prof!
