### ISSUE TITLE
Week 12 Quiz Results

### ISSUE THREAD

**Issue by chaosInTheWild** [nus-cs2113-AY1920S2/forum#99]
Hello,
It seems I am unable to view the results for the week 12 quiz in LumiNUS and also cannot see the questions I got correct or wrong even though its past the closing time of the quiz.

**Comment by damithc** [comment]
Thanks for the alert @kokjoon97 
Enabled it just now.

**Comment by chaosInTheWild** [comment]
Its still not working for me for some reason though

**Comment by damithc** [comment]
Opps, set it 11.59 PM instead of AM. Try now.

**Comment by chaosInTheWild** [comment]
It works now! Thank you prof!
